Config.IgnoreClasses = {
    [13] = true, -- Cycles
    [14] = true, -- Boats
    [15] = true, -- Helicopters
    [16] = true, -- Planes
    [21] = true, -- Trains
}

Config.WheelBones = {
    [0] = 'wheel_lf',
    [1] = 'wheel_rf',
    [2] = 'wheel_lm',
    [3] = 'wheel_rm',
    [4] = 'wheel_lr',
    [5] = 'wheel_rr',
    --[45] = '',
    --[46] = ''
}

Config.HornLabels = {
    [0] = 'Truck Horn',
    [1] = 'Cop Horn',
    [2] = 'Clown Horn',
    [3] = 'Musical Horn 1',
    [4] = 'Musical Horn 2',
    [5] = 'Musical Horn 3',
    [6] = 'Musical Horn 4',
    [7] = 'Musical Horn 5',
    [8] = 'Sad Trombone',
    [9] = 'Classical Horn 1',
    [10] = 'Classical Horn 2',
    [11] = 'Classical Horn 3',
    [12] = 'Classical Horn 4',
    [13] = 'Classical Horn 5',
    [14] = 'Classical Horn 6',
    [15] = 'Classical Horn 7',
    [16] = 'Scale - Do',
    [17] = 'Scale - Re',
    [18] = 'Scale - Mi',
    [19] = 'Scale - Fa',
    [20] = 'Scale - Sol',
    [21] = 'Scale - La',
    [22] = 'Scale - Ti',
    [23] = 'Scale - Do',
    [24] = 'Jazz Horn 1',
    [25] = 'Jazz Horn 2',
    [26] = 'Jazz Horn 3',
    [27] = 'Jazz Horn Loop',
    [28] = 'Star Spangled Banner 1',
    [29] = 'Star Spangled Banner 2',
    [30] = 'Star Spangled Banner 3',
    [31] = 'Star Spangled Banner 4',
    [32] = 'Classical Horn 8 Loop',
    [33] = 'Classical Horn 9 Loop',
    [34] = 'Classical Horn 10 Loop',
    [35] = 'Classical Horn 8',
    [36] = 'Classical Horn 9',
    [37] = 'Classical Horn 10',
    [38] = 'Funeral Loop',
    [39] = 'Funeral',
    [40] = 'Spooky Loop',
    [41] = 'Spooky',
    [42] = 'San Andreas Loop',
    [43] = 'San Andreas',
    [44] = 'Liberty City Loop',
    [45] = 'Liberty City',
    [46] = 'Festive 1 Loop',
    [47] = 'Festive 1',
    [48] = 'Festive 2 Loop',
    [49] = 'Festive 2',
    [50] = 'Festive 3 Loop',
    [51] = 'Festive 3',
}

-- https://docs.fivem.net/natives/?_0xB3ED1BFB4BE636DC
Config.WheelCategories = {
    { label = 'Sport',               id = 0 },
    { label = 'Muscle',              id = 1 },
    { label = 'Lowrider',            id = 2 },
    { label = 'SUV',                 id = 3 },
    { label = 'Tout-Terrain',        id = 4 },
    { label = 'Tuning',              id = 5 },
    { label = 'Moto',                id = 6 },
    { label = 'Haut de Gamme',       id = 7 },
    { label = 'Classiques de Benny', id = 8 },
    { label = 'Sur-Mesure de Benny', id = 9 },
    { label = 'Monoplace',           id = 10 },
    { label = 'Street',              id = 11 },
    { label = 'Piste',               id = 12 },    
}

-- https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD
Config.InteriorCategories = {
    { label = 'Arceau de Securite',  id = 5 },
    { label = 'Klaxons',             id = 14 },
    { label = 'Caisson de Basses',   id = 19 },
    { label = 'Tableau de Bord',     id = 29 },
    { label = 'Cadran',              id = 30 },
    { label = 'Haut-parleur de Porte', id = 31 },
    { label = 'Sieges',              id = 32 },
    { label = 'Volant',              id = 33 },
    { label = 'Levier de Vitesse',   id = 34 },
    { label = 'Plaque',              id = 35 },
    { label = 'Haut-parleur',        id = 36 },
}

-- https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD
Config.ExteriorCategories = {
    { label = 'Aileron',              id = 0 },
    { label = 'Pare-chocs Avant',     id = 1 },
    { label = 'Pare-chocs Arriere',   id = 2 },
    { label = 'Bas de Caisse',        id = 3 },
    { label = 'Echappement',          id = 4 },
    { label = 'Grille',               id = 6 },
    { label = 'Capot',                id = 7 },
    { label = 'Aile Gauche',          id = 8 },
    { label = 'Aile Droite',          id = 9 },
    { label = 'Toit',                 id = 10 },
    { label = 'Hydrauliques',         id = 21 },
    { label = 'Phares',               id = 22 },
    { label = 'Fumee des Pneus',      id = 20 },
    { label = 'Roues Arriere',        id = 24 },
    { label = 'Support de Plaque',    id = 25 },
    { label = 'Plaques Personnalisees', id = 26 },
    { label = 'Garniture A',          id = 27 },
    { label = 'Ornements',            id = 28 },
    { label = 'Coffre',               id = 37 },
    { label = 'Hydraulique',          id = 38 },
    { label = 'Bloc Moteur',          id = 39 },
    { label = 'Filtre a Air',         id = 40 },
    { label = 'Jambe de Force',       id = 41 },
    { label = 'Cache de Passage de Roue', id = 42 },
    { label = 'Antenne',              id = 43 },
    { label = 'Garniture B',          id = 44 },
    { label = 'Reservoir de Carburant', id = 45 },
    { label = 'Fenetre',              id = 46 },
    { label = 'Porte',                id = 47 },
    { label = 'Livree',               id = 48 },
    { label = 'Gyrophare',            id = 49 },
    { label = 'Peinture',             id = 50 },
}

-- https://docs.fivem.net/natives/?_0x3DFF319A831E0CDB
Config.Xenon = {
    { label = 'Defaut',         id = -1 },
    { label = 'Blanc',          id = 0 },
    { label = 'Bleu',           id = 1 },
    { label = 'Bleu electrique', id = 2 },
    { label = 'Vert Menthe',     id = 3 },
    { label = 'Vert Citron',     id = 4 },
    { label = 'Jaune',           id = 5 },
    { label = 'Doree',           id = 6 },
    { label = 'Orange',          id = 7 },
    { label = 'Rouge',           id = 8 },
    { label = 'Rose Poney',      id = 9 },
    { label = 'Rose Fuchsia',    id = 10 },
    { label = 'Violet',          id = 11 },
    { label = 'Lumiere Noire',   id = 12 },
}

-- https://docs.fivem.net/natives/?_0x57C51E6BAD752696
Config.WindowTints = {
    { label = 'Aucun',           id = 0 },
    { label = 'Noir Pur',        id = 1 },
    { label = 'Fumee Foncee',    id = 2 },
    { label = 'Fumee Claire',    id = 3 },
    { label = 'Standard',        id = 4 },
    { label = 'Limousine',       id = 5 },
    { label = 'Vert',            id = 6 },
}

-- https://docs.fivem.net/natives/?_0x9088EB5A43FFB0A1
Config.PlateIndexes = {
    { label = 'Bleu sur Blanc 1',  id = 0 },
    { label = 'Jaune sur Noir',    id = 1 },
    { label = 'Jaune sur Bleu',    id = 2 },
    { label = 'Bleu sur Blanc 2',  id = 3 },
    { label = 'Bleu sur Blanc 3',  id = 4 },
    { label = 'Yankton',           id = 5 },
}

-- https://docs.fivem.net/natives/?_0x2AA720E4287BF269
Config.Neon = {
    { label = 'Gauche', id = 0 },
    { label = 'Droite', id = 1 },
    { label = 'Avant',  id = 2 },
    { label = 'Arriere', id = 3 },
}

-- https://docs.fivem.net/natives/?_0x8E0A582209A62695
Config.NeonColors = {
    { label = 'Blanc',          r = 222, g = 222, b = 255 },
    { label = 'Bleu',           r = 2,   g = 21,  b = 255 },
    { label = 'Bleu Electrique', r = 3,   g = 83,  b = 255 },
    { label = 'Vert Menthe',     r = 0,   g = 255, b = 140 },
    { label = 'Vert Citron',     r = 94,  g = 255, b = 1 },
    { label = 'Jaune',           r = 255, g = 255, b = 0 },
    { label = 'Doree',    r = 255, g = 150, b = 0 },
    { label = 'Orange',          r = 255, g = 62,  b = 0 },
    { label = 'Rouge',           r = 255, g = 1,   b = 1 },
    { label = 'Rose Poney',      r = 255, g = 50,  b = 100 },
    { label = 'Rose Fuchsia',    r = 255, g = 5,   b = 190 },
    { label = 'Violet',          r = 35,  g = 1,   b = 255 },
    { label = 'Lumiere Noire',   r = 15,  g = 3,   b = 255 },
}

-- https://docs.fivem.net/natives/?_0xB5BA80F839791C0F
Config.TyreSmoke = {
    { label = 'Fumee Blanche',   r = 254, g = 254, b = 254 },
    { label = 'Fumee Noire',     r = 1,   g = 1,   b = 1 },
    { label = 'Fumee Bleue',     r = 0,   g = 150, b = 255 },
    { label = 'Fumee Jaune',     r = 255, g = 255, b = 50 },
    { label = 'Fumee Orange',    r = 255, g = 153, b = 51 },
    { label = 'Fumee Rouge',     r = 255, g = 10,  b = 10 },
    { label = 'Fumee Verte',     r = 10,  g = 255, b = 10 },
    { label = 'Fumee Violette',  r = 153, g = 10,  b = 153 },
    { label = 'Fumee Rose',      r = 255, g = 102, b = 178 },
    { label = 'Fumee Grise',     r = 128, g = 128, b = 128 },

}

Config.Paints = {

    Metallic = {
        { label = 'Noir Metallique',                   id = 0,   hex = '0d1116' },
        { label = 'Noir Graphite Metallique',          id = 1,   hex = '1c1d21' },
        { label = 'Acier Noir Metallique',             id = 2,   hex = '32383d' },
        { label = 'Argent Fonce Metallique',           id = 3,   hex = '454b4f' },
        { label = 'Argent Metallique',                 id = 4,   hex = '999da0' },
        { label = 'Argent Bleu Metallique',            id = 5,   hex = 'c2c4c6' },
        { label = 'Gris Acier Metallique',             id = 6,   hex = '979a97' },
        { label = 'Gris Ombre Metallique',             id = 7,   hex = '637380' },
        { label = 'Gris Pierre Metallique',            id = 8,   hex = '63625c' },
        { label = 'Argent Minuit Metallique',          id = 9,   hex = '3c3f47' },
        { label = 'Gris Canon Metallique',             id = 10,  hex = '444e54' },
        { label = 'Gris Anthracite Metallique',        id = 11,  hex = '1d2129' },
        { label = 'Rouge Metallique',                  id = 27,  hex = 'c00e1a' },
        { label = 'Rouge Torino Metallique',           id = 28,  hex = 'da1918' },
        { label = 'Rouge Formula Metallique',          id = 29,  hex = 'b6111b' },
        { label = 'Rouge Flamboyant Metallique',       id = 30,  hex = 'a51e23' },
        { label = 'Rouge Gracieux Metallique',         id = 31,  hex = '7b1a22' },
        { label = 'Rouge Grenat Metallique',           id = 32,  hex = '8e1b1f' },
        { label = 'Rouge Desert Metallique',           id = 33,  hex = '6f1818' },
        { label = 'Rouge Cabernet Metallique',         id = 34,  hex = '49111d' },
        { label = 'Rouge Bonbon Metallique',           id = 35,  hex = 'b60f25' },
        { label = 'Orange Lever de Soleil Metallique', id = 36,  hex = 'd44a17' },
        { label = 'Or Classique Metallique',           id = 37,  hex = 'c2944f' },
        { label = 'Orange Metallique',                 id = 38,  hex = 'f78616' },
        { label = 'Vert Fonce Metallique',             id = 49,  hex = '132428' },
        { label = 'Vert Course Metallique',            id = 50,  hex = '122e2b' },
        { label = 'Vert Mer Metallique',               id = 51,  hex = '12383c' },
        { label = 'Vert Olive Metallique',             id = 52,  hex = '31423f' },
        { label = 'Vert Metallique',                   id = 53,  hex = '155c2d' },
        { label = 'Vert Bleu Essence Metallique',      id = 54,  hex = '1b6770' },
        { label = 'Bleu Minuit Metallique',            id = 61,  hex = '222e46' },
        { label = 'Bleu Fonce Metallique',             id = 62,  hex = '233155' },
        { label = 'Bleu Saxe Metallique',              id = 63,  hex = '304c7e' },
        { label = 'Bleu Metallique',                   id = 64,  hex = '47578f' },
        { label = 'Bleu Marinier Metallique',          id = 65,  hex = '637ba7' },
        { label = 'Bleu Port Metallique',              id = 66,  hex = '394762' },
        { label = 'Bleu Diamant Metallique',           id = 67,  hex = 'd6e7f1' },
        { label = 'Bleu Surf Metallique',              id = 68,  hex = '76afbe' },
        { label = 'Bleu Nautique Metallique',          id = 69,  hex = '345e72' },
        { label = 'Bleu Brillant Metallique',          id = 70,  hex = '0b9cf1' },
        { label = 'Bleu Violet Metallique',            id = 71,  hex = '2f2d52' },
        { label = 'Bleu Spinnaker Metallique',         id = 72,  hex = '282c4d' },
        { label = 'Bleu Ultra Metallique',             id = 73,  hex = '2354a1' },
        { label = 'Bleu Brillant Metallique',          id = 74,  hex = '6ea3c6' },
        { label = 'Jaune Taxi Metallique',             id = 88,  hex = 'ffcf20' },
        { label = 'Jaune Course Metallique',           id = 89,  hex = 'fbe212' },
        { label = 'Bronze Metallique',                 id = 90,  hex = '916532' },
        { label = 'Jaune Oiseau Metallique',           id = 91,  hex = 'e0e13d' },
        { label = 'Vert Citron Metallique',            id = 92,  hex = '98d223' },
        { label = 'Champagne Metallique',              id = 93,  hex = '9b8c78' },
        { label = 'Beige Pueblo Metallique',           id = 94,  hex = '503218' },
        { label = 'Ivoire Fonce Metallique',           id = 95,  hex = '473f2b' },
        { label = 'Marron Choco Metallique',           id = 96,  hex = '221b19' },
        { label = 'Marron Dore Metallique',            id = 97,  hex = '653f23' },
        { label = 'Marron Clair Metallique',           id = 98,  hex = '775c3e' },
        { label = 'Beige Paille Metallique',           id = 99,  hex = 'ac9975' },
        { label = 'Marron Mousse Metallique',          id = 100, hex = '6c6b4b' },
        { label = 'Marron Biston Metallique',          id = 101, hex = '402e2b' },
        { label = 'Bois de Hetre Metallique',          id = 102, hex = 'a4965f' },
        { label = 'Bois de Hetre Fonce Metallique',    id = 103, hex = '46231a' },
        { label = 'Orange Choco Metallique',           id = 104, hex = '752b19' },
        { label = 'Sable de Plage Metallique',         id = 105, hex = 'bfae7b' },
        { label = 'Sable Blanchi au Soleil Metallique', id = 106, hex = 'dfd5b2' },
        { label = 'Creme Metallique',                  id = 107, hex = 'f7edd5' },
        { label = 'Blanc Metallique',                  id = 111, hex = 'fffff6' },
        { label = 'Blanc Givre Metallique',            id = 112, hex = 'eaeaea' },
        { label = 'Vert Securicor Metallique',         id = 125, hex = '83c566' },
        { label = 'Rose Vermillon Metallique',         id = 137, hex = 'df5891' },
        { label = 'Bleu Noir Metallique',              id = 141, hex = '0a0c17' },
        { label = 'Violet Noir Metallique',            id = 142, hex = '0c0d18' },
        { label = 'Rouge Noir Metallique',             id = 143, hex = '0e0d14' },
        { label = 'Violet Metallique',                 id = 145, hex = '621276' },
        { label = 'Bleu Tres Fonce Metallique',        id = 146, hex = '0b1421' },
        { label = 'Rouge Lave Metallique',             id = 150, hex = 'bc1917' }
        
    },

    Matte = {
        { label = 'Noir Mat',               id = 12,  hex = '13181f' },
        { label = 'Gris Mat',               id = 13,  hex = '26282a' },
        { label = 'Gris Clair Mat',         id = 14,  hex = '515554' },
        { label = 'Rouge Mat',              id = 39,  hex = 'cf1f21' },
        { label = 'Rouge Fonce Mat',        id = 40,  hex = '732021' },
        { label = 'Orange Mat',             id = 41,  hex = 'f27d20' },
        { label = 'Jaune Mat',              id = 42,  hex = 'ffc91f' },
        { label = 'Vert Citron Mat',        id = 55,  hex = '66b81f' },
        { label = 'Bleu Fonce Mat',         id = 82,  hex = '1f2852' },
        { label = 'Bleu Mat',               id = 83,  hex = '253aa7' },
        { label = 'Bleu Minuit Mat',        id = 84,  hex = '1c3551' },
        { label = 'Vert Mat',               id = 128, hex = '4e6443' },
        { label = 'Marron Mat',             id = 129, hex = 'bcac8f' },
        { label = 'Blanc Mat',              id = 131, hex = 'fcf9f1' },
        { label = 'Violet Mat',             id = 148, hex = '6b1f7b' },
        { label = 'Violet Fonce Mat',       id = 149, hex = '1e1d22' },
        { label = 'Vert Foret Mat',         id = 151, hex = '2d362a' },
        { label = 'Olive Drab Mat',         id = 152, hex = '696748' },
        { label = 'Marron Desert Mat',      id = 153, hex = '7a6c55' },
        { label = 'Beige Desert Mat',       id = 154, hex = 'c3b492' },
        { label = 'Vert Feuillage Mat',     id = 155, hex = '5a6352' }
    },

    Util = {
        { label = 'Noir Util',              id = 15,  hex = '151921' },
        { label = 'Noir Poly Util',         id = 16,  hex = '1e2429' },
        { label = 'Argent Fonce Util',      id = 17,  hex = '333a3c' },
        { label = 'Argent Util',            id = 18,  hex = '8c9095' },
        { label = 'Metal de Guerre Util',   id = 19,  hex = '39434d' },
        { label = 'Argent Ombre Util',      id = 20,  hex = '506272' },
        { label = 'Rouge Util',             id = 43,  hex = '9c1016' },
        { label = 'Rouge Clair Util',       id = 44,  hex = 'de0f18' },
        { label = 'Rouge Grenat Util',      id = 45,  hex = '8f1e17' },
        { label = 'Vert Fonce Util',        id = 56,  hex = '22383e' },
        { label = 'Vert Util',              id = 57,  hex = '1d5a3f' },
        { label = 'Bleu Fonce Util',        id = 75,  hex = '112552' },
        { label = 'Bleu Minuit Util',       id = 76,  hex = '1b203e' },
        { label = 'Bleu Util',              id = 77,  hex = '275190' },
        { label = 'Bleu Mer Util',          id = 78,  hex = '608592' },
        { label = 'Bleu eclair Util',       id = 79,  hex = '2446a8' },
        { label = 'Maui Blue Poly Util',    id = 80,  hex = '4271e1' },
        { label = 'Bleu Clair Util',        id = 81,  hex = '3b39e0' },
        { label = 'Marron Util',            id = 108, hex = '3a2a1b' },
        { label = 'Marron Moyen Util',      id = 109, hex = '785f33' },
        { label = 'Marron Clair Util',      id = 110, hex = 'b5a079' },
        { label = 'Blanc Casse Util',       id = 122, hex = 'dfddd0' }
    },

    Worn = {
        { label = 'Noir Use',             id = 21,  hex = '1e232f' },
        { label = 'Graphite Use',         id = 22,  hex = '363a3f' },
        { label = 'Gris Argent Use',      id = 23,  hex = 'a0a199' },
        { label = 'Argent Use',           id = 24,  hex = 'd3d3d3' },
        { label = 'Bleu Argent Use',      id = 25,  hex = 'b7bfca' },
        { label = 'Argent Ombre Use',     id = 26,  hex = '778794' },
        { label = 'Rouge Use',            id = 46,  hex = 'a94744' },
        { label = 'Rouge Dore Us',       id = 47,  hex = 'b16c51' },
        { label = 'Rouge Fonc Us',      id = 48,  hex = '371c25' },
        { label = 'Vert Fonce Us',       id = 58,  hex = '2d423f' },
        { label = 'Vert Use',             id = 59,  hex = '45594b' },
        { label = 'Mer Foncee Usee',      id = 60,  hex = '65867f' },
        { label = 'Bleu Fonce Use',       id = 85,  hex = '4c5f81' },
        { label = 'Bleu Use',             id = 86,  hex = '58688e' },
        { label = 'Bleu Clair Use',       id = 87,  hex = '74b5d8' },
        { label = 'Miel Beige Use',       id = 113, hex = 'b0ab94' },
        { label = 'Marron Use',           id = 114, hex = '453831' },
        { label = 'Marron Fonce Use',     id = 115, hex = '2a282b' },
        { label = 'Beige Paille Use',     id = 116, hex = '726c57' },
        { label = 'Blanc Casse Use',      id = 121, hex = 'eae6de' },
        { label = 'Orange Use',           id = 123, hex = 'f2ad2e' },
        { label = 'Orange Clair Use',     id = 124, hex = 'f9a458' },
        { label = 'Jaune Taxi Use',       id = 126, hex = 'f1cc40' },
        { label = 'Orange Use',           id = 130, hex = 'f8b658' },
        { label = 'Blanc Use',            id = 132, hex = 'fffffb' },
        { label = 'Vert Armee Olive Use', id = 133, hex = '81844c' }
    },

    Misc = {
        { label = 'Acier Brosse',         id = 117, hex = '6a747c' },
        { label = 'Acier Noir Brosse',    id = 118, hex = '354158' },
        { label = 'Aluminium Brosse',     id = 119, hex = '9ba0a8' },
        { label = 'Chrome',               id = 120, hex = '5870a1' },
        { label = 'Bleu Voiture de Police', id = 127, hex = '4cc3da' },
        { label = 'Blanc Pur',            id = 134, hex = 'ffffff' },
        { label = 'Rose Fluo',            id = 135, hex = 'f21f99' },
        { label = 'Rose Saumon',          id = 136, hex = 'fdd6cd' },
        { label = 'Orange',               id = 138, hex = 'f6ae20' },
        { label = 'Vert',                 id = 139, hex = 'b0ee6e' },
        { label = 'Bleu',                 id = 140, hex = '08e9fa' },
        { label = 'Vert Chasseur',        id = 144, hex = '9f9e8a' },
        { label = 'Noir Mod Shop',        id = 147, hex = '11141a' },
        { label = 'Alliage',              id = 156, hex = '81827f' },
        { label = 'Bleu Epsilon',         id = 157, hex = 'afd6e4' },
        { label = 'Or Pur',               id = 158, hex = '7a6440' },
        { label = 'Or Brosse',            id = 159, hex = '7f6a48' }
        
    },

    Chameleon = {
        { label = 'Anodized Red',           id = 161, hex = 'CF1020' },
        { label = 'Anodized Wine',          id = 162, hex = '5E1224' },
        { label = 'Anodized Purple',        id = 163, hex = '800080' },
        { label = 'Anodized Blue',          id = 164, hex = '0000FF' },
        { label = 'Anodized Green',         id = 165, hex = '008000' },
        { label = 'Anodized Lime',          id = 166, hex = 'AFFF00' },
        { label = 'Anodized Copper',        id = 167, hex = 'B87333' },
        { label = 'Anodized Bronze',        id = 168, hex = 'CD7F32' },
        { label = 'Anodized Champagne',     id = 169, hex = 'F7E7CE' },
        { label = 'Anodized Gold',          id = 170, hex = 'FFD700' },
        { label = 'Green Blue Flip',        id = 171, hex = '1164B4' },
        { label = 'Green Red Flip',         id = 172, hex = 'B43104' },
        { label = 'Green Brown Flip',       id = 173, hex = '735C12' },
        { label = 'Green Turquoise Flip',   id = 174, hex = '43C6DB' },
        { label = 'Green Purple Flip',      id = 175, hex = '9D00FF' },
        { label = 'Teal Purple Flip',       id = 176, hex = '6A0DAD' },
        { label = 'Turquoise Red Flip',     id = 177, hex = 'E60026' },
        { label = 'Turquoise Purple Flip',  id = 178, hex = '30D5C8' },
        { label = 'Cyan Purple Flip',       id = 179, hex = '0FF0FC' },
        { label = 'Blue Pink Flip',         id = 180, hex = '4C2882' },
        { label = 'Blue Green Flip',        id = 181, hex = '138808' },
        { label = 'Purple Red Flip',        id = 182, hex = '9B111E' },
        { label = 'Purple Green Flip',      id = 183, hex = '6B2E53' },
        { label = 'Magenta Green Flip',     id = 184, hex = 'CA1F7B' },
        { label = 'Magenta Yellow Flip',    id = 185, hex = 'FEDF00' },
        { label = 'Burgundy Green Flip',    id = 186, hex = '900020' },
        { label = 'Magenta Cyan Flip',      id = 187, hex = '00FFA1' },
        { label = 'Copper Purple Flip',     id = 188, hex = 'B87333' },
        { label = 'Magenta Orange Flip',    id = 189, hex = 'FF5F1F' },
        { label = 'Red Orange Flip',        id = 190, hex = 'FF4500' },
        { label = 'Orange Purple Flip',     id = 191, hex = 'B04080' },
        { label = 'Orange Blue Flip',       id = 192, hex = '0047AB' },
        { label = 'White Purple Flip',      id = 193, hex = 'F8F0E3' },
        { label = 'Red Rainbow Flip',       id = 194, hex = 'ED2939' },
        { label = 'Blue Rainbow Flip',      id = 195, hex = '4B0082' },
        { label = 'Dark Green Pearl',       id = 196, hex = '013220' },
        { label = 'Dark Teal Pearl',        id = 197, hex = '008080' },
        { label = 'Dark Blue Pearl',        id = 198, hex = '000080' },
        { label = 'Dark Purple Pearl',      id = 199, hex = '301934' },
        { label = 'Oil Slick Pearl',        id = 200, hex = '4B0082' },
        { label = 'Light Green Pearl',      id = 201, hex = '99E550' },
        { label = 'Light Blue Pearl',       id = 202, hex = 'ADD8E6' },
        { label = 'Light Purple Pearl',     id = 203, hex = '967BB6' },
        { label = 'Light Pink Pearl',       id = 203, hex = 'FFB6C1' },
        { label = 'Off White Pearl',        id = 204, hex = 'F2F0E6' },
        { label = 'Pink Pearl',             id = 205, hex = 'EAADEA' },
        { label = 'Yellow Pearl',           id = 206, hex = 'FFF000' },
        { label = 'Green Pearl',            id = 207, hex = '00A550' },
        { label = 'Blue Pearl',             id = 208, hex = '0000FF' },
        { label = 'Cream Pearl',            id = 209, hex = 'FFFDD0' },
        { label = 'White Prismatic',        id = 210, hex = 'FFFFFF' },
        { label = 'Graphite Prismatic',     id = 211, hex = '251607' },
        { label = 'Dark Blue Prismatic',    id = 212, hex = '00008B' },
        { label = 'Dark Purple Prismatic',  id = 213, hex = '301934' },
        { label = 'Hot Pink Prismatic',     id = 214, hex = 'FF69B4' },
        { label = 'Dark Red Prismatic',     id = 215, hex = '8B0000' },
        { label = 'Dark GREEN Prismatic',   id = 216, hex = '013220' },
        { label = 'Black Prismatic',        id = 217, hex = '000000' },
        { label = 'Black Oil Spill',        id = 218, hex = '121212' },
        { label = 'Black Rainbow',          id = 219, hex = '000000' },
        { label = 'Prismatic',              id = 220, hex = 'CCCCCC' },
        { label = 'Black Holographic',      id = 221, hex = '101010' },
        { label = 'White Holographic',      id = 222, hex = 'E6E8FA' },
        { label = 'Monochrome',             id = 223, hex = 'B4B4B4' },
        { label = 'Night & Day',            id = 224, hex = '333366' },
        { label = 'The Verlierer',          id = 225, hex = '550055' },
        { label = 'Sprunk Extreme',         id = 226, hex = '00FF00' },
        { label = 'Vice City',              id = 227, hex = 'FF00FF' },
        { label = 'Synthwave Nights',       id = 228, hex = 'FF007F' },
        { label = 'Four Seasons',           id = 229, hex = '73C2FB' },
        { label = 'Maisonette 9 Throwback', id = 230, hex = 'DCDCDC' },
        { label = 'Bubblegum',              id = 231, hex = 'FFC0CB' },
        { label = 'Full Rainbow',           id = 232, hex = 'FF0000' },
        { label = 'Sunset',                 id = 233, hex = 'FFD700' },
        { label = 'The Seven',              id = 234, hex = '701C1C' },
        { label = 'Kamen Rider',            id = 235, hex = '1C1C70' },
        { label = 'Chromatic Aberration',   id = 236, hex = 'D8BFD8' },
        { label = "It's Christmas",         id = 237, hex = 'FF0000' },
        { label = 'Temperature',            id = 238, hex = 'FFA07A' },
        { label = 'Yellow Orange Pearl',    id = 239, hex = 'FFAE42' },
        { label = 'Pink Blue Pearl',        id = 240, hex = 'D8BFD8' },
        { label = 'Green Blue Pearl',       id = 241, hex = '3CB371' },
        { label = 'Turquoise Black Pearl',  id = 242, hex = '00CED1' }
    },
}

if Config.ColorFavorites then
    Config.Paints.Favorites = { -- add your favorite custom colors here by hex
        { label = 'My Custom Paint Name!', hex = '' }
    }
end
