Config = Config or {}

Config.ShortCalls = true -- Dispatch notifications are sent containing only the alert name, omitting additional details. For more information, the dispatch menu can be accessed.  
Config.Debug = false -- Enables debug and send alerts when leo break the law.

Config.RespondKeybind = 'E'
Config.OpenDispatchMenu = 'O'
Config.AlertTime = 5     -- Specify the duration for the alert to appear on the screen. The default time is 5 seconds for all alerts. To set a different duration for specific alerts, change the value in `alertTime = nil` found in the alerts.lua file.

Config.MaxCallList = 25 -- maximum dispatch calls in dispatch list
Config.OnDutyOnly = true -- Set true if only on duty players can see the alert
Config.Jobs = { -- Job Types or names that can access the dispatch menu. If you want to allow more jobs to see certain dispatch alerts. Go to alerts.lua and add the job name to the alert.
    "leo",
    "ems"
}

Config.DefaultAlertsDelay = 5 -- Delay between each default alert, prevent spamming
Config.DefaultAlerts = {
    Speeding = true,
    Shooting = true,
    Autotheft = true,
    Melee = true,
    PlayerDowned = true,
    Explosion = true
}

Config.MinOffset = 1
Config.MaxOffset = 120

Config.PhoneRequired = true -- Set true if only can use 911/311 command when got a phone on inventory.
Config.PhoneItems = { -- Add the entire list of your phone items.
    'classic_phone',
    'black_phone',
    'blue_phone',
    'gold_phone',
    'red_phone',
    'green_phone',
    'greenlight_phone',
    'pink_phone',
    'white_phone',
}

-- Locations for the Hunting Zones and No Dispatch Zones( Label: Name of Blip // Radius: Radius of the Alert and Blip)
Config.EnableHuntingBlip = false

Config.Locations = {
    ["HuntingZones"] = {
        [1] = {label = "Zone de chasse", radius = 650.0, coords = vector3(-938.61, 4823.99, 313.92)},
    },
    ["NoDispatchZones"] = {
        [1] = {label = "Ammunation 1", coords = vector3(13.53, -1097.92, 29.8), length = 14.0, width = 5.0, heading = 70, minZ = 28.8, maxZ = 32.8},
        [2] = {label = "Ammunation 2", coords = vector3(821.96, -2163.09, 29.62), length = 14.0, width = 5.0, heading = 270, minZ = 28.62, maxZ = 32.62},
    },
}

-- Whitelist Guns that do not send shooting alerts
Config.WeaponWhitelist = {
    'WEAPON_GRENADE',
    'WEAPON_BZGAS',
    'WEAPON_MOLOTOV',
    'WEAPON_STICKYBOMB',
    'WEAPON_PROXMINE',
    'WEAPON_SNOWBALL',
    'WEAPON_PIPEBOMB',
    'WEAPON_BALL',
    'WEAPON_SMOKEGRENADE',
    'WEAPON_FLARE',
    'WEAPON_PETROLCAN',
    'WEAPON_FIREEXTINGUISHER',
    'WEAPON_HAZARDCAN',
    'WEAPON_RAYCARBINE',
    'WEAPON_STUNGUN'
}

Config.Blips = {
    ['vehicleshots'] = { -- Need to match the codeName in alerts.lua
        radius = 0,
        sprite = 119,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['shooting'] = {
        radius = 0,
        sprite = 110,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['speeding'] = {
        radius = 0,
        sprite = 326,
        color = 84,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['fight'] = {
        radius = 0,
        sprite = 685,
        color = 69,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['civdown'] = {
        radius = 0,
        sprite = 126,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'dispatch',
        offset = false,
        flash = false
    },
    ['civdead'] = {
        radius = 0,
        sprite = 126,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'dispatch',
        offset = false,
        flash = false
    },
    ['911call'] = {
        radius = 0,
        sprite = 480,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['311call'] = {
        radius = 0,
        sprite = 480,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['officerdown'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['officerbackup'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['officerdistress'] = {
        radius = 15.0,
        sprite = 526,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = true
    },
    ['emsdown'] = {
        radius = 15.0,
        sprite = 526,
        color = 3,
        scale = 1.5,
        length = 2,
        sound = 'panicbutton',
        offset = false,
        flash = false
    },
    ['hunting'] = {
        radius = 0,
        sprite = 141,
        color = 2,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['storerobbery'] = {
        radius = 0,
        sprite = 52,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['bankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 2,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['paletobankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 12,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['pacificbankrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 5,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['prisonbreak'] = {
        radius = 0,
        sprite = 189,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vangelicorobbery'] = {
        radius = 0,
        sprite = 434,
        color = 5,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['houserobbery'] = {
        radius = 0,
        sprite = 40,
        color = 5,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['suspicioushandoff'] = {
        radius = 120.0,
        sprite = 469,
        color = 52,
        scale = 0,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = true,
        flash = false
    },
    ['yachtheist'] = {
        radius = 0,
        sprite = 455,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vehicletheft'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['signrobbery'] = {
        radius = 0,
        sprite = 358,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['susactivity'] = {
        radius = 0,
        sprite = 66,
        color = 37,
        scale = 0.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    -- Rainmad Scripts
    ['artgalleryrobbery'] = {
        radius = 0,
        sprite = 269,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['humanelabsrobbery'] = {
        radius = 0,
        sprite = 499,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['trainrobbery'] = {
        radius = 0,
        sprite = 667,
        color = 78,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['vanrobbery'] = {
        radius = 0,
        sprite = 67,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['undergroundrobbery'] = {
        radius = 0,
        sprite = 486,
        color = 59,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['drugboatrobbery'] = {
        radius = 0,
        sprite = 427,
        color = 26,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['unionrobbery'] = {
        radius = 0,
        sprite = 500,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'robberysound',
        offset = false,
        flash = false
    },
    ['carboosting'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['carjack'] = {
        radius = 0,
        sprite = 595,
        color = 60,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = false,
        flash = false
    },
    ['explosion'] = {
        radius = 75.0,
        sprite = 436,
        color = 1,
        scale = 1.5,
        length = 2,
        sound = 'Lose_1st',
        sound2 = 'GTAO_FM_Events_Soundset',
        offset = true,
        flash = false
    }
}

Config.Colors = {
    ['0'] = "Noir Métallique",
    ['1'] = "Noir Graphite Métallique",
    ['2'] = "Acier Noir Métallique",
    ['3'] = "Argent Foncé Métallique",
    ['4'] = "Argent Métallique",
    ['5'] = "Argent Bleu Métallique",
    ['6'] = "Gris Acier Métallique",
    ['7'] = "Argent Ombre Métallique",
    ['8'] = "Argent Pierre Métallique",
    ['9'] = "Argent Minuit Métallique",
    ['10'] = "Métal Gris Canon",
    ['11'] = "Gris Anthracite Métallique",
    ['12'] = "Noir Mat",
    ['13'] = "Gris Mat",
    ['14'] = "Gris Clair Mat",
    ['15'] = "Noir Utilitaire",
    ['16'] = "Poly Noir Utilitaire",
    ['17'] = "Argent Foncé Utilitaire",
    ['18'] = "Argent Utilitaire",
    ['19'] = "Métal Gris Canon Utilitaire",
    ['20'] = "Argent Ombre Utilitaire",
    ['21'] = "Noir Usé",
    ['22'] = "Graphite Usé",
    ['23'] = "Gris Argent Usé",
    ['24'] = "Argent Usé",
    ['25'] = "Argent Bleu Usé",
    ['26'] = "Argent Ombre Usé",
    ['27'] = "Rouge Métallique",
    ['28'] = "Rouge Torino Métallique",
    ['29'] = "Rouge Formule Métallique",
    ['30'] = "Rouge Flamme Métallique",
    ['31'] = "Rouge Élégant Métallique",
    ['32'] = "Rouge Grenat Métallique",
    ['33'] = "Rouge Désert Métallique",
    ['34'] = "Rouge Cabernet Métallique",
    ['35'] = "Rouge Bonbon Métallique",
    ['36'] = "Orange Lever du Soleil Métallique",
    ['37'] = "Or Classique Métallique",
    ['38'] = "Orange Métallique",
    ['39'] = "Rouge Mat",
    ['40'] = "Rouge Sombre Mat",
    ['41'] = "Orange Mat",
    ['42'] = "Jaune Mat",
    ['43'] = "Rouge Utilitaire",
    ['44'] = "Rouge Vif Utilitaire",
    ['45'] = "Rouge Grenat Utilitaire",
    ['46'] = "Rouge Usé",
    ['47'] = "Rouge Doré Usé",
    ['48'] = "Rouge Foncé Usé",
    ['49'] = "Vert Foncé Métallique",
    ['50'] = "Vert Course Métallique",
    ['51'] = "Vert Mer Métallique",
    ['52'] = "Vert Olive Métallique",
    ['53'] = "Vert Métallique",
    ['54'] = "Vert Essence Bleu Métallique",
    ['55'] = "Vert Citron Mat",
    ['56'] = "Vert Foncé Utilitaire",
    ['57'] = "Vert Utilitaire",
    ['58'] = "Vert Foncé Usé",
    ['59'] = "Vert Usé",
    ['60'] = "Mer Légère Usée",
    ['61'] = "Bleu Minuit Métallique",
    ['62'] = "Bleu Sombre Métallique",
    ['63'] = "Bleu Saxony Métallique",
    ['64'] = "Bleu Métallique",
    ['65'] = "Bleu Mariner Métallique",
    ['66'] = "Bleu Harbour Métallique",
    ['67'] = "Bleu Diamant Métallique",
    ['68'] = "Bleu Surf Métallique",
    ['69'] = "Bleu Nautique Métallique",
    ['70'] = "Bleu Clair Métallique",
    ['71'] = "Bleu Violet Métallique",
    ['72'] = "Bleu Spinnaker Métallique",
    ['73'] = "Bleu Ultra Métallique",
    ['74'] = "Bleu Clair Métallique",
    ['75'] = "Bleu Foncé Utilitaire",
    ['76'] = "Bleu Minuit Utilitaire",
    ['77'] = "Bleu Utilitaire",
    ['78'] = "Bleu Mousse de Mer Utilitaire",
    ['79'] = "Bleu Foudre Utilitaire",
    ['80'] = "Bleu Maui Poly Utilitaire",
    ['81'] = "Bleu Vif Utilitaire",
    ['82'] = "Bleu Sombre Mat",
    ['83'] = "Bleu Mat",
    ['84'] = "Bleu Minuit Mat",
    ['85'] = "Bleu Foncé Usé",
    ['86'] = "Bleu Usé",
    ['87'] = "Bleu Clair Usé",
    ['88'] = "Jaune Taxi Métallique",
    ['89'] = "Jaune Course Métallique",
    ['90'] = "Bronze Métallique",
    ['91'] = "Oiseau Jaune Métallique",
    ['92'] = "Citron Métallique",
    ['93'] = "Champagne Métallique",
    ['94'] = "Beige Pueblo Métallique",
    ['95'] = "Ivoire Sombre Métallique",
    ['96'] = "Marron Choco Métallique",
    ['97'] = "Marron Doré Métallique",
    ['98'] = "Marron Clair Métallique",
    ['99'] = "Beige Paille Métallique",
    ['100'] = "Marron Mousse Métallique",
    ['101'] = "Marron Biston Métallique",
    ['102'] = "Hêtre Métallique",
    ['103'] = "Hêtre Sombre Métallique",
    ['104'] = "Choco Orange Métallique",
    ['105'] = "Sable Plage Métallique",
    ['106'] = "Sable Décoloré Métallique",
    ['107'] = "Crème Métallique",
    ['108'] = "Marron Utilitaire",
    ['109'] = "Marron Moyen Utilitaire",
    ['110'] = "Marron Clair Utilitaire",
    ['111'] = "Blanc Métallique",
    ['112'] = "Blanc Givré Métallique",
    ['113'] = "Miel Beige Usé",
    ['114'] = "Marron Usé",
    ['115'] = "Marron Foncé Usé",
    ['116'] = "Beige Paille Usé",
    ['117'] = "Acier Brossé",
    ['118'] = "Acier Noir Brossé",
    ['119'] = "Aluminium Brossé",
    ['120'] = "Chrome",
    ['121'] = "Blanc Cassé Usé",
    ['122'] = "Blanc Cassé Utilitaire",
    ['123'] = "Orange Usé",
    ['124'] = "Orange Clair Usé",
    ['125'] = "Vert Securicor Métallique",
    ['126'] = "Jaune Taxi Usé",
    ['127'] = "Bleu Voiture de Police",
    ['128'] = "Vert Mat",
    ['129'] = "Marron Mat",
    ['130'] = "Orange Usé",
    ['131'] = "Blanc Mat",
    ['132'] = "Blanc Usé",
    ['133'] = "Vert Olive Militaire Usé",
    ['134'] = "Blanc Pur",
    ['135'] = "Rose Fluo",
    ['136'] = "Rose Saumon",
    ['137'] = "Rose Vermillon Métallique",
    ['138'] = "Orange",
    ['139'] = "Vert",
    ['140'] = "Bleu",
    ['141'] = "Noir Bleu Métallique",
    ['142'] = "Noir Violet Métallique",
    ['143'] = "Noir Rouge Métallique",
    ['144'] = "Vert Chasseur",
    ['145'] = "Violet Métallique",
    ['146'] = "Bleu Sombre Métallique",
    ['147'] = "Noir",
    ['148'] = "Violet Mat",
    ['149'] = "Violet Sombre Mat",
    ['150'] = "Rouge Lave Métallique",
    ['151'] = "Vert Forêt Mat",
    ['152'] = "Olive Drab Mat",
    ['153'] = "Marron Désert Mat",
    ['154'] = "Beige Désert Mat",
    ['155'] = "Vert Feuillage Mat",
    ['156'] = "Couleur Alliage Par Défaut",
    ['157'] = "Bleu Epsilon",
    ['158'] = "Or Pur",
    ['159'] = "Or Brossé",
    ['160'] = "MP100"
}
