QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = false -- false: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Indépendant', payment = 10 } } },
	-- bus = { label = 'Bus', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	judge = { label = 'Juge', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Intérim', payment = 100 } } },
	-- trucker = { label = 'Trucker', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	-- tow = { label = 'Towing', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	-- garbage = { label = 'Garbage', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	avocat = { label = 'Avocat', defaultDuty = false, offDutyPay = false, grades = { ['0'] = { name = 'Intérim', payment = 50 } } },


	police = {
		label = 'LSPD',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Officier I', payment = 50 },
			['2'] = { name = 'Officier II', payment = 50 },
			['3'] = { name = 'Officier III', payment = 50 },
			['4'] = { name = 'Sergent', payment = 50 },
			['5'] = { name = 'Lieutenant', payment = 50 },
			['6'] = { name = 'Capitaine', payment = 50 },
			['7'] = { name = 'Commandant', payment = 50 },
			['8'] = { name = 'Chef Adjoint', isboss = true, payment = 50 },
			['9'] = { name = 'Chef de la Police', isboss = true, payment = 50 },
		},
	},
	sherif = {
		label = 'Shérif',
		type = 'leo',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Officier I', payment = 50 },
			['2'] = { name = 'Officier II', payment = 50 },
			['3'] = { name = 'Officier III', payment = 50 },
			['4'] = { name = 'Sergent', payment = 50 },
			['5'] = { name = 'Lieutenant', payment = 50 },
			['6'] = { name = 'Capitaine', payment = 50 },
			['7'] = { name = 'Commandant', payment = 50 },
			['8'] = { name = 'Chef Adjoint', isboss = true, payment = 50 },
			['9'] = { name = 'Chef', isboss = true, payment = 50 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'En formation', payment = 50 },
			['2'] = { name = 'Secouriste', payment = 50 },
			['3'] = { name = 'EMS', payment = 50 },
			['4'] = { name = 'EMS confirmé', payment = 50 },
			['5'] = { name = 'Interne', payment = 50 },
			['6'] = { name = 'Médecin', payment = 50 },
			['7'] = { name = 'Chirurgien', payment = 50 },
			['8'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['9'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	ems = {
		label = 'EMS Paleto',
		type = 'ems',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'En formation', payment = 50 },
			['2'] = { name = 'Secouriste', payment = 50 },
			['3'] = { name = 'EMS', payment = 50 },
			['4'] = { name = 'EMS confirmé', payment = 50 },
			['5'] = { name = 'Interne', payment = 50 },
			['6'] = { name = 'Médecin', payment = 50 },
			['7'] = { name = 'Chirurgien', payment = 50 },
			['8'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['9'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	gouv = {
		label = 'Gouvernement',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Représentant des Employés', payment = 50 },
			['1'] = { name = 'Représentant des Entrepreneurs', payment = 50 },
			['2'] = { name = 'Représentant EMS', payment = 50 },
			['3'] = { name = 'Représentant Police', payment = 50 },
			['4'] = { name = 'Commissaire', payment = 50 },
			['5'] = { name = 'Vice-gouverneur', isboss = true, payment = 50 },
			['6'] = { name = 'Gouverneur', isboss = true, payment = 50 },
		},
	},
	realestate = {
		label = 'Dynasty 8',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Locations', payment = 50 },
			['2'] = { name = 'Ventes', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Conducteur I', payment = 50 },
			['2'] = { name = 'Conducteur II', payment = 50 },
			['3'] = { name = 'Conducteur d\'évenement', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	cardealer = {
		label = 'Concessionnaire',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Locations', payment = 50 },
			['2'] = { name = 'Vendeur I', payment = 50 },
			['3'] = { name = 'Vendeur II', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	mechanic = {
		label = 'Mecano',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	lscustom = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	mcdonald = {
		label = 'MC Donald',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	unicorn = {
		label = 'Vanilla Unicorn',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	bahamas = {
		label = 'Bahamas Mamas',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	vineyard = {
		label = 'Vigneron',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
	reporter = {
		label = 'Weazel News',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Novice', payment = 50 },
			['2'] = { name = 'Employé', payment = 50 },
			['3'] = { name = 'Expérimenté', payment = 50 },
			['4'] = { name = 'Co-Directeur', isboss = true, payment = 50 },
			['5'] = { name = 'Directeur', isboss = true, payment = 50 },
		},
	},
}
