QBCore = exports['qb-core']:GetCoreObject()

-- App qs smartphone
RegisterNetEvent('qb-jobmenu:client:alertepoliceduty', function()
    ExecuteCommand('17')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertegendarmerieduty', function()
    ExecuteCommand('017')
    Wait(100)
    openJobMenu()
end)
RegisterNetEvent('qb-jobmenu:client:alerteambulanceduty', function()
    ExecuteCommand('15')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertepompierduty', function()
    ExecuteCommand('18')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alerterealestateduty', function()
    ExecuteCommand('0525488234')
    Wait(100)
    openJobMenu()
end)
 
RegisterNetEvent('qb-jobmenu:client:alertetaxiduty', function()
    ExecuteCommand('0974670002')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertecardealerduty', function()
    ExecuteCommand('0974670003')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertedirduty', function()
    ExecuteCommand('0974670069')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertevinciduty', function()
    ExecuteCommand('0186471398')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertenorautoduty', function()
    ExecuteCommand('0974670036')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:alertebrinksduty', function()
    ExecuteCommand('0186766957')
    Wait(100)
    openJobMenu()
end)

RegisterNetEvent('qb-jobmenu:client:scenemenu', function()
    Wait(100)
    ExecuteCommand('scenemenu')
end)