INSERT IGNORE INTO `dealerships_creator_classes` (`id`, `label`) VALUES
	('boats', 'Boats'),
	('commercial', 'Commercial'),
	('compacts', 'Compacts'),
	('coupes', 'Coupes'),
	('cycles', 'Cycles'),
	('emergency', 'Emergency'),
	('helicopters', 'Helicopters'),
	('industrial', 'Industrial'),
	('military', 'Military'),
	('motorcycles', 'Motorcycles'),
	('muscle', 'Muscle'),
	('off_road', 'Off-Road'),
	('open_wheels', 'Open Wheels'),
	('planes', 'Planes'),
	('sedans', 'Sedans'),
	('service', 'Service'),
	('sports', 'Sports'),
	('sports_classics', 'Sports Classics'),
	('super', 'Super'),
	('suvs', 'SUVs'),
	('utility', 'Utility'),
	('vans', 'Vans');