INSERT IGNORE INTO `dealerships_creator_vehicles` (`spawn_name`, `label`, `class`, `type`) VALUES
	('adder', 'Adder', 'super', 'car'),
	('airbus', 'Airport Bus', 'service', 'car'),
	('airtug', 'Airtug', 'utility', 'car'),
	('akuma', 'Akuma', 'motorcycles', 'car'),
	('alkonost', 'RO-86 Alkonost', 'planes', 'air'),
	('alpha', 'Alpha', 'sports', 'car'),
	('alphaz1', 'Alpha-Z1', 'planes', 'air'),
	('ambulance', 'Ambulance', 'emergency', 'car'),
	('apc', 'APC', 'military', 'car'),
	('ardent', 'Ardent', 'sports_classics', 'car'),
	('armytanker', 'Army Trailer', 'utility', 'car'),
	('armytrailer', 'Army Trailer', 'utility', 'car'),
	('armytrailer2', 'Army Trailer', 'utility', 'car'),
	('asbo', 'Asbo', 'compacts', 'car'),
	('asea', 'Asea', 'sedans', 'car'),
	('asea2', 'Asea', 'sedans', 'car'),
	('asterope', 'Asterope', 'sedans', 'car'),
	('astron', 'Astron', 'suvs', 'car'),
	('autarch', 'Autarch', 'super', 'car'),
	('avarus', 'Avarus', 'motorcycles', 'car'),
	('avenger', 'Avenger', 'planes', 'air'),
	('avenger2', 'Avenger', 'planes', 'air'),
	('avisa', 'Avisa', 'boats', 'boat'),
	('bagger', 'Bagger', 'motorcycles', 'car'),
	('baletrailer', 'Baletrailer', 'utility', 'car'),
	('baller', 'Baller', 'suvs', 'car'),
	('baller2', 'Baller', 'suvs', 'car'),
	('baller3', 'Baller LE', 'suvs', 'car'),
	('baller4', 'Baller LE LWB', 'suvs', 'car'),
	('baller5', 'Baller LE (Armored)', 'suvs', 'car'),
	('baller6', 'Baller LE LWB (Armored)', 'suvs', 'car'),
	('baller7', 'Baller ST', 'suvs', 'car'),
	('banshee', 'Banshee', 'sports', 'car'),
	('banshee2', 'Banshee 900R', 'super', 'car'),
	('barracks', 'Barracks', 'military', 'car'),
	('barracks2', 'Barracks Semi', 'military', 'car'),
	('barracks3', 'Barracks', 'military', 'car'),
	('barrage', 'Barrage', 'military', 'car'),
	('bati', 'Bati 801', 'motorcycles', 'car'),
	('bati2', 'Bati 801RR', 'motorcycles', 'car'),
	('benson', 'Benson', 'commercial', 'car'),
	('besra', 'Besra', 'planes', 'air'),
	('bestiagts', 'Bestia GTS', 'sports', 'car'),
	('bf400', 'BF400', 'motorcycles', 'car'),
	('bfinjection', 'Injection', 'off_road', 'car'),
	('biff', 'Biff', 'commercial', 'car'),
	('bifta', 'Bifta', 'off_road', 'car'),
	('bison', 'Bison', 'vans', 'car'),
	('bison2', 'Bison', 'vans', 'car'),
	('bison3', 'Bison', 'vans', 'car'),
	('bjxl', 'BeeJay XL', 'suvs', 'car'),
	('blade', 'Blade', 'muscle', 'car'),
	('blazer', 'Blazer', 'off_road', 'car'),
	('blazer2', 'Blazer Lifeguard', 'off_road', 'car'),
	('blazer3', 'Hot Rod Blazer', 'off_road', 'car'),
	('blazer4', 'Street Blazer', 'off_road', 'car'),
	('blazer5', 'Blazer Aqua', 'off_road', 'car'),
	('blimp', 'Atomic Blimp', 'planes', 'air'),
	('blimp2', 'Xero Blimp', 'planes', 'air'),
	('blimp3', 'Blimp', 'planes', 'air'),
	('blista', 'Blista', 'compacts', 'car'),
	('blista2', 'Blista Compact', 'sports', 'car'),
	('blista3', 'Go Go Monkey Blista', 'sports', 'car'),
	('bmx', 'BMX', 'cycles', 'car'),
	('boattrailer', 'Boat Trailer', 'utility', 'car'),
	('bobcatxl', 'Bobcat XL', 'vans', 'car'),
	('bodhi2', 'Bodhi', 'off_road', 'car'),
	('bombushka', 'RM-10 Bombushka', 'planes', 'air'),
	('boor', 'Boor', 'off_road', 'car'),
	('boxville', 'Boxville', 'vans', 'car'),
	('boxville2', 'Boxville', 'vans', 'car'),
	('boxville3', 'Boxville', 'vans', 'car'),
	('boxville4', 'Boxville', 'vans', 'car'),
	('boxville5', 'Armored Boxville', 'vans', 'car'),
	('brawler', 'Brawler', 'off_road', 'car'),
	('brickade', 'Brickade', 'service', 'car'),
	('brickade2', 'Brickade 6x6', 'service', 'car'),
	('brioso', 'Brioso R/A', 'compacts', 'car'),
	('brioso2', 'Brioso 300', 'compacts', 'car'),
	('brioso3', 'Brioso 300 Widebody', 'compacts', 'car'),
	('broadway', 'Broadway', 'muscle', 'car'),
	('btype', 'Roosevelt', 'sports_classics', 'car'),
	('btype2', 'Fränken Stange', 'sports_classics', 'car'),
	('btype3', 'Roosevelt Valor', 'sports_classics', 'car'),
	('buccaneer', 'Buccaneer', 'muscle', 'car'),
	('buccaneer2', 'Buccaneer Custom', 'muscle', 'car'),
	('buffalo', 'Buffalo', 'sports', 'car'),
	('buffalo2', 'Buffalo S', 'sports', 'car'),
	('buffalo3', 'Sprunk Buffalo', 'sports', 'car'),
	('buffalo4', 'Buffalo STX', 'muscle', 'car'),
	('bulldozer', 'Dozer', 'industrial', 'car'),
	('bullet', 'Bullet', 'super', 'car'),
	('burrito', 'Burrito', 'vans', 'car'),
	('burrito2', 'Bugstars Burrito', 'vans', 'car'),
	('burrito3', 'Burrito', 'vans', 'car'),
	('burrito4', 'Burrito', 'vans', 'car'),
	('burrito5', 'Burrito', 'vans', 'car'),
	('bus', 'Bus', 'service', 'car'),
	('buzzard2', 'Buzzard', 'helicopters', 'air'),
	('caddy', 'Caddy', 'utility', 'car'),
	('caddy2', 'Caddy', 'utility', 'car'),
	('caddy3', 'Caddy', 'utility', 'car'),
	('calico', 'Calico GTF', 'sports', 'car'),
	('camper', 'Camper', 'vans', 'car'),
	('caracara', 'Caracara', 'off_road', 'car'),
	('caracara2', 'Caracara 4x4', 'off_road', 'car'),
	('carbonizzare', 'Carbonizzare', 'sports', 'car'),
	('carbonrs', 'Carbon RS', 'motorcycles', 'car'),
	('cargobob', 'Cargobob', 'helicopters', 'air'),
	('cargobob2', 'Cargobob', 'helicopters', 'air'),
	('cargobob3', 'Cargobob', 'helicopters', 'air'),
	('cargobob4', 'Cargobob', 'helicopters', 'air'),
	('cargoplane', 'Cargo Plane', 'planes', 'air'),
	('cargoplane2', 'Cargo Plane', 'planes', 'air'),
	('casco', 'Casco', 'sports_classics', 'car'),
	('cavalcade', 'Cavalcade', 'suvs', 'car'),
	('cavalcade2', 'Cavalcade', 'suvs', 'car'),
	('champion', 'Champion', 'super', 'car'),
	('cheburek', 'Cheburek', 'sports_classics', 'car'),
	('cheetah', 'Cheetah', 'super', 'car'),
	('cheetah2', 'Cheetah Classic', 'sports_classics', 'car'),
	('chernobog', 'Chernobog', 'military', 'car'),
	('chimera', 'Chimera', 'motorcycles', 'car'),
	('chino', 'Chino', 'muscle', 'car'),
	('chino2', 'Chino Custom', 'muscle', 'car'),
	('cinquemila', 'Cinquemila', 'sedans', 'car'),
	('cliffhanger', 'Cliffhanger', 'motorcycles', 'car'),
	('clique', 'Clique', 'muscle', 'car'),
	('club', 'Club', 'compacts', 'car'),
	('coach', 'Dashound', 'service', 'car'),
	('cog55', 'Cognoscenti 55', 'sedans', 'car'),
	('cog552', 'Cognoscenti 55 (Armored)', 'sedans', 'car'),
	('cogcabrio', 'Cognoscenti Cabrio', 'coupes', 'car'),
	('cognoscenti', 'Cognoscenti', 'sedans', 'car'),
	('cognoscenti2', 'Cognoscenti (Armored)', 'sedans', 'car'),
	('comet2', 'Comet', 'sports', 'car'),
	('comet3', 'Comet Retro Custom', 'sports', 'car'),
	('comet4', 'Comet Safari', 'sports', 'car'),
	('comet5', 'Comet SR', 'sports', 'car'),
	('comet6', 'Comet S2', 'sports', 'car'),
	('comet7', 'Comet S2 Cabrio', 'sports', 'car'),
	('conada', 'Conada', 'helicopters', 'air'),
	('contender', 'Contender', 'suvs', 'car'),
	('coquette', 'Coquette', 'sports', 'car'),
	('coquette2', 'Coquette Classic', 'sports_classics', 'car'),
	('coquette3', 'Coquette BlackFin', 'muscle', 'car'),
	('coquette4', 'Coquette D10', 'sports', 'car'),
	('corsita', 'Corsita', 'sports', 'car'),
	('cruiser', 'Cruiser', 'cycles', 'car'),
	('crusader', 'Crusader', 'military', 'car'),
	('cuban800', 'Cuban 800', 'planes', 'air'),
	('cutter', 'Cutter', 'industrial', 'car'),
	('cyclone', 'Cyclone', 'super', 'car'),
	('cypher', 'Cypher', 'sports', 'car'),
	('daemon', 'Daemon', 'motorcycles', 'car'),
	('daemon2', 'Daemon', 'motorcycles', 'car'),
	('deathbike', 'Apocalypse Deathbike', 'motorcycles', 'car'),
	('deathbike2', 'Future Shock Deathbike', 'motorcycles', 'car'),
	('deathbike3', 'Nightmare Deathbike', 'motorcycles', 'car'),
	('defiler', 'Defiler', 'motorcycles', 'car'),
	('deity', 'Deity', 'sedans', 'car'),
	('deluxo', 'Deluxo', 'sports_classics', 'car'),
	('deveste', 'Deveste Eight', 'super', 'car'),
	('deviant', 'Deviant', 'muscle', 'car'),
	('diablous', 'Diabolus', 'motorcycles', 'car'),
	('diablous2', 'Diabolus Custom', 'motorcycles', 'car'),
	('dilettante', 'Dilettante', 'compacts', 'car'),
	('dilettante2', 'Dilettante', 'compacts', 'car'),
	('dinghy', 'Dinghy', 'boats', 'boat'),
	('dinghy2', 'Dinghy', 'boats', 'boat'),
	('dinghy3', 'Dinghy', 'boats', 'boat'),
	('dinghy4', 'Dinghy', 'boats', 'boat'),
	('dinghy5', 'Weaponized Dinghy', 'boats', 'boat'),
	('dloader', 'Duneloader', 'off_road', 'car'),
	('docktrailer', 'DOCKTRAILER', 'utility', 'car'),
	('docktug', 'Docktug', 'utility', 'car'),
	('dodo', 'Dodo', 'planes', 'air'),
	('dominator', 'Dominator', 'muscle', 'car'),
	('dominator2', 'Pisswasser Dominator', 'muscle', 'car'),
	('dominator3', 'Dominator GTX', 'muscle', 'car'),
	('dominator4', 'Apocalypse Dominator', 'muscle', 'car'),
	('dominator5', 'Future Shock Dominator', 'muscle', 'car'),
	('dominator6', 'Nightmare Dominator', 'muscle', 'car'),
	('dominator7', 'Dominator ASP', 'muscle', 'car'),
	('dominator8', 'Dominator GTT', 'muscle', 'car'),
	('double', 'Double-T', 'motorcycles', 'car'),
	('drafter', '8F Drafter', 'sports', 'car'),
	('draugur', 'Draugur', 'off_road', 'car'),
	('dubsta', 'Dubsta', 'suvs', 'car'),
	('dubsta2', 'Dubsta', 'suvs', 'car'),
	('dubsta3', 'Dubsta 6x6', 'off_road', 'car'),
	('dukes', 'Dukes', 'muscle', 'car'),
	('dukes2', "Duke O 'Death", 'muscle', 'car'),
	('dukes3', 'Beater Dukes', 'muscle', 'car'),
	('dump', 'Dump', 'industrial', 'car'),
	('dune', 'Dune Buggy', 'off_road', 'car'),
	('dune2', 'Space Docker', 'off_road', 'car'),
	('dune3', 'Dune FAV', 'off_road', 'car'),
	('dune4', 'Ramp Buggy', 'off_road', 'car'),
	('dune5', 'Ramp Buggy', 'off_road', 'car'),
	('duster', 'Duster', 'planes', 'air'),
	('dynasty', 'Dynasty', 'sports_classics', 'car'),
	('elegy', 'Elegy Retro Custom', 'sports', 'car'),
	('elegy2', 'Elegy RH8', 'sports', 'car'),
	('ellie', 'Ellie', 'muscle', 'car'),
	('emerus', 'Emerus', 'super', 'car'),
	('emperor', 'Emperor', 'sedans', 'car'),
	('emperor2', 'Emperor', 'sedans', 'car'),
	('emperor3', 'Emperor', 'sedans', 'car'),
	('enduro', 'Enduro', 'motorcycles', 'car'),
	('entity2', 'Entity XXR', 'super', 'car'),
	('entity3', 'Entity MT', 'super', 'car'),
	('entityxf', 'Entity XF', 'super', 'car'),
	('esskey', 'Esskey', 'motorcycles', 'car'),
	('eudora', 'Eudora', 'muscle', 'car'),
	('euros', 'Euros', 'sports', 'car'),
	('everon', 'Everon', 'off_road', 'car'),
	('everon2', 'Hotring Everon', 'sports', 'car'),
	('exemplar', 'Exemplar', 'coupes', 'car'),
	('f620', 'F620', 'coupes', 'car'),
	('faction', 'Faction', 'muscle', 'car'),
	('faction2', 'Faction Custom', 'muscle', 'car'),
	('faction3', 'Faction Custom Donk', 'muscle', 'car'),
	('fagaloa', 'Fagaloa', 'sports_classics', 'car'),
	('faggio', 'Faggio Sport', 'motorcycles', 'car'),
	('faggio2', 'Faggio', 'motorcycles', 'car'),
	('faggio3', 'Faggio Mod', 'motorcycles', 'car'),
	('fbi', 'FIB', 'emergency', 'car'),
	('fbi2', 'FIB', 'emergency', 'car'),
	('fcr', 'FCR 1000', 'motorcycles', 'car'),
	('fcr2', 'FCR 1000 Custom', 'motorcycles', 'car'),
	('felon', 'Felon', 'coupes', 'car'),
	('felon2', 'Felon GT', 'coupes', 'car'),
	('feltzer2', 'Feltzer', 'sports', 'car'),
	('feltzer3', 'Stirling GT', 'sports_classics', 'car'),
	('firetruk', 'Fire Truck', 'emergency', 'car'),
	('fixter', 'Fixter', 'cycles', 'car'),
	('flashgt', 'Flash GT', 'sports', 'car'),
	('flatbed', 'Flatbed', 'industrial', 'car'),
	('fmj', 'FMJ', 'super', 'car'),
	('forklift', 'Forklift', 'utility', 'car'),
	('formula', 'PR4', 'open_wheels', 'car'),
	('formula2', 'R88', 'open_wheels', 'car'),
	('fq2', 'FQ 2', 'suvs', 'car'),
	('freecrawler', 'Freecrawler', 'off_road', 'car'),
	('freighttrailer', 'FREIGHTTRAI', 'utility', 'car'),
	('frogger', 'Frogger', 'helicopters', 'air'),
	('frogger2', 'Frogger', 'helicopters', 'air'),
	('fugitive', 'Fugitive', 'sedans', 'car'),
	('furia', 'Furia', 'super', 'car'),
	('furoregt', 'Furore GT', 'sports', 'car'),
	('fusilade', 'Fusilade', 'sports', 'car'),
	('futo', 'Futo', 'sports', 'car'),
	('futo2', 'Futo GTX', 'sports', 'car'),
	('gargoyle', 'Gargoyle', 'motorcycles', 'car'),
	('gauntlet', 'Gauntlet', 'muscle', 'car'),
	('gauntlet2', 'Redwood Gauntlet', 'muscle', 'car'),
	('gauntlet3', 'Gauntlet Classic', 'muscle', 'car'),
	('gauntlet4', 'Gauntlet Hellfire', 'muscle', 'car'),
	('gauntlet5', 'Gauntlet Classic Custom', 'muscle', 'car'),
	('gb200', 'GB200', 'sports', 'car'),
	('gburrito', 'Gang Burrito', 'vans', 'car'),
	('gburrito2', 'Gang Burrito', 'vans', 'car'),
	('glendale', 'Glendale', 'sedans', 'car'),
	('glendale2', 'Glendale Custom', 'sedans', 'car'),
	('gp1', 'GP1', 'super', 'car'),
	('graintrailer', 'GRAINTRAILE', 'utility', 'car'),
	('granger', 'Granger', 'suvs', 'car'),
	('granger2', 'Granger 3600LX', 'suvs', 'car'),
	('greenwood', 'Greenwood', 'muscle', 'car'),
	('gresley', 'Gresley', 'suvs', 'car'),
	('growler', 'Growler', 'sports', 'car'),
	('gt500', 'GT500', 'sports_classics', 'car'),
	('guardian', 'Guardian', 'industrial', 'car'),
	('habanero', 'Habanero', 'suvs', 'car'),
	('hakuchou', 'Hakuchou', 'motorcycles', 'car'),
	('hakuchou2', 'Hakuchou Drag', 'motorcycles', 'car'),
	('halftrack', 'Half-track', 'military', 'car'),
	('handler', 'Dock Handler', 'industrial', 'car'),
	('hauler', 'Hauler', 'commercial', 'car'),
	('hauler2', 'Hauler Custom', 'commercial', 'car'),
	('havok', 'Havok', 'helicopters', 'air'),
	('hellion', 'Hellion', 'off_road', 'car'),
	('hermes', 'Hermes', 'muscle', 'car'),
	('hexer', 'Hexer', 'motorcycles', 'car'),
	('hotknife', 'Hotknife', 'muscle', 'car'),
	('hotring', 'Hotring Sabre', 'sports', 'car'),
	('howard', 'Howard NX-25', 'planes', 'air'),
	('hunter', 'FH-1 Hunter', 'helicopters', 'air'),
	('huntley', 'Huntley S', 'suvs', 'car'),
	('hustler', 'Hustler', 'muscle', 'car'),
	('hydra', 'Hydra', 'planes', 'air'),
	('ignus', 'Ignus', 'super', 'car'),
	('imorgon', 'Imorgon', 'sports', 'car'),
	('impaler', 'Impaler', 'muscle', 'car'),
	('infernus', 'Infernus', 'super', 'car'),
	('infernus2', 'Infernus Classic', 'sports_classics', 'car'),
	('ingot', 'Ingot', 'sedans', 'car'),
	('innovation', 'Innovation', 'motorcycles', 'car'),
	('insurgent', 'Insurgent Pick-Up', 'off_road', 'car'),
	('insurgent2', 'Insurgent', 'off_road', 'car'),
	('insurgent3', 'Insurgent Pick-Up Custom', 'off_road', 'car'),
	('intruder', 'Intruder', 'sedans', 'car'),
	('issi2', 'Issi', 'compacts', 'car'),
	('issi3', 'Issi Classic', 'compacts', 'car'),
	('issi7', 'Issi Sport', 'sports', 'car'),
	('issi8', 'Issi Rally', 'suvs', 'car'),
	('italigtb', 'Itali GTB', 'super', 'car'),
	('italigtb2', 'Itali GTB Custom', 'super', 'car'),
	('italigto', 'Itali GTO', 'sports', 'car'),
	('italirsx', 'Itali RSX', 'sports', 'car'),
	('iwagen', 'I-Wagen', 'suvs', 'car'),
	('jackal', 'Jackal', 'coupes', 'car'),
	('jb700', 'JB 700', 'sports_classics', 'car'),
	('jb7002', 'JB 700W', 'sports_classics', 'car'),
	('jester', 'Jester', 'sports', 'car'),
	('jester2', 'Jester (Racecar)', 'sports', 'car'),
	('jester3', 'Jester Classic', 'sports', 'car'),
	('jester4', 'Jester RR', 'sports', 'car'),
	('jet', 'Jet', 'planes', 'air'),
	('jetmax', 'Jetmax', 'boats', 'boat'),
	('journey', 'Journey', 'vans', 'car'),
	('journey2', 'Journey II', 'vans', 'car'),
	('jubilee', 'Jubilee', 'suvs', 'car'),
	('jugular', 'Jugular', 'sports', 'car'),
	('kalahari', 'Kalahari', 'off_road', 'car'),
	('kamacho', 'Kamacho', 'off_road', 'car'),
	('kanjo', 'Blista Kanjo', 'compacts', 'car'),
	('kanjosj', 'Kanjo SJ', 'coupes', 'car'),
	('khamelion', 'Khamelion', 'sports', 'car'),
	('khanjali', 'TM-02 Khanjali', 'military', 'car'),
	('komoda', 'Komoda', 'sports', 'car'),
	('kosatka', 'Kosatka', 'boats', 'boat'),
	('krieger', 'Krieger', 'super', 'car'),
	('kuruma', 'Kuruma', 'sports', 'car'),
	('kuruma2', 'Kuruma (Armored)', 'sports', 'car'),
	('landstalker', 'Landstalker', 'suvs', 'car'),
	('landstalker2', 'Landstalker XL', 'suvs', 'car'),
	('lazer', 'P-996 LAZER', 'planes', 'air'),
	('le7b', 'RE-7B', 'super', 'car'),
	('lectro', 'Lectro', 'motorcycles', 'car'),
	('lguard', 'Lifeguard', 'emergency', 'car'),
	('limo2', 'Turreted Limo', 'sedans', 'car'),
	('lm87', 'LM87', 'super', 'car'),
	('locust', 'Locust', 'sports', 'car'),
	('longfin', 'Longfin', 'boats', 'boat'),
	('lurcher', 'Lurcher', 'muscle', 'car'),
	('luxor', 'Luxor', 'planes', 'air'),
	('luxor2', 'Luxor Deluxe', 'planes', 'air'),
	('lynx', 'Lynx', 'sports', 'car'),
	('mamba', 'Mamba', 'sports_classics', 'car'),
	('mammatus', 'Mammatus', 'planes', 'air'),
	('manana', 'Manana', 'sports_classics', 'car'),
	('manana2', 'Manana Custom', 'muscle', 'car'),
	('manchez', 'Manchez', 'motorcycles', 'car'),
	('manchez2', 'Manchez Scout', 'motorcycles', 'car'),
	('manchez3', 'Manchez Scout C', 'motorcycles', 'car'),
	('marquis', 'Marquis', 'boats', 'boat'),
	('marshall', 'Marshall', 'off_road', 'car'),
	('massacro', 'Massacro', 'sports', 'car'),
	('massacro2', 'Massacro (Racecar)', 'sports', 'car'),
	('maverick', 'Maverick', 'helicopters', 'air'),
	('menacer', 'Menacer', 'off_road', 'car'),
	('mesa', 'Mesa', 'suvs', 'car'),
	('mesa2', 'Mesa', 'suvs', 'car'),
	('mesa3', 'Mesa', 'off_road', 'car'),
	('michelli', 'Michelli GT', 'sports_classics', 'car'),
	('microlight', 'Ultralight', 'planes', 'air'),
	('miljet', 'Miljet', 'planes', 'air'),
	('minitank', 'Invade and Persuade Tank', 'military', 'car'),
	('minivan', 'Minivan', 'vans', 'car'),
	('minivan2', 'Minivan Custom', 'vans', 'car'),
	('mixer', 'Mixer', 'industrial', 'car'),
	('mixer2', 'Mixer', 'industrial', 'car'),
	('mogul', 'Mogul', 'planes', 'air'),
	('molotok', 'V-65 Molotok', 'planes', 'air'),
	('monroe', 'Monroe', 'sports_classics', 'car'),
	('monster', 'Liberator', 'off_road', 'car'),
	('monster3', 'Apocalypse Sasquatch', 'off_road', 'car'),
	('monster4', 'Future Shock Sasquatch', 'off_road', 'car'),
	('monster5', 'Nightmare Sasquatch', 'off_road', 'car'),
	('moonbeam', 'Moonbeam', 'muscle', 'car'),
	('moonbeam2', 'Moonbeam Custom', 'muscle', 'car'),
	('mower', 'Lawn Mower', 'utility', 'car'),
	('mule', 'Mule', 'commercial', 'car'),
	('mule2', 'Mule', 'commercial', 'car'),
	('mule3', 'Mule', 'commercial', 'car'),
	('mule4', 'Mule Custom', 'commercial', 'car'),
	('mule5', 'Mule', 'commercial', 'car'),
	('nebula', 'Nebula Turbo', 'sports_classics', 'car'),
	('nemesis', 'Nemesis', 'motorcycles', 'car'),
	('neo', 'Neo', 'sports', 'car'),
	('neon', 'Neon', 'sports', 'car'),
	('nero', 'Nero', 'super', 'car'),
	('nero2', 'Nero Custom', 'super', 'car'),
	('nightblade', 'Nightblade', 'motorcycles', 'car'),
	('nightshade', 'Nightshade', 'muscle', 'car'),
	('nightshark', 'Nightshark', 'off_road', 'car'),
	('nimbus', 'Nimbus', 'planes', 'air'),
	('ninef', '9F', 'sports', 'car'),
	('ninef2', '9F Cabrio', 'sports', 'car'),
	('nokota', 'P-45 Nokota', 'planes', 'air'),
	('novak', 'Novak', 'suvs', 'car'),
	('omnis', 'Omnis', 'sports', 'car'),
	('omnisegt', 'Omnis e-GT', 'sports', 'car'),
	('openwheel1', 'BR8', 'open_wheels', 'car'),
	('openwheel2', 'DR1', 'open_wheels', 'car'),
	('oracle', 'Oracle XS', 'coupes', 'car'),
	('oracle2', 'Oracle', 'coupes', 'car'),
	('osiris', 'Osiris', 'super', 'car'),
	('outlaw', 'Outlaw', 'off_road', 'car'),
	('packer', 'Packer', 'commercial', 'car'),
	('panthere', 'Panthere', 'sports', 'car'),
	('panto', 'Panto', 'compacts', 'car'),
	('paradise', 'Paradise', 'vans', 'car'),
	('paragon', 'Paragon R', 'sports', 'car'),
	('paragon2', 'Paragon R (Armored)', 'sports', 'car'),
	('pariah', 'Pariah', 'sports', 'car'),
	('patriot', 'Patriot', 'suvs', 'car'),
	('patriot2', 'Patriot Stretch', 'suvs', 'car'),
	('patriot3', 'Patriot Mil-Spec', 'off_road', 'car'),
	('patrolboat', 'Kurtz 31 Patrol Boat', 'boats', 'boat'),
	('pbus', 'Prison Bus', 'emergency', 'car'),
	('pbus2', 'Festival Bus', 'service', 'car'),
	('pcj', 'PCJ 600', 'motorcycles', 'car'),
	('penetrator', 'Penetrator', 'super', 'car'),
	('penumbra', 'Penumbra', 'sports', 'car'),
	('penumbra2', 'Penumbra FF', 'sports', 'car'),
	('peyote', 'Peyote', 'sports_classics', 'car'),
	('peyote2', 'Peyote Gasser', 'muscle', 'car'),
	('peyote3', 'Peyote Custom', 'sports_classics', 'car'),
	('pfister811', '811', 'super', 'car'),
	('phantom', 'Phantom', 'commercial', 'car'),
	('phantom3', 'Phantom Custom', 'commercial', 'car'),
	('phoenix', 'Phoenix', 'muscle', 'car'),
	('picador', 'Picador', 'muscle', 'car'),
	('pigalle', 'Pigalle', 'sports_classics', 'car'),
	('police', 'Police Cruiser', 'emergency', 'car'),
	('police2', 'Police Cruiser', 'emergency', 'car'),
	('police3', 'Police Cruiser', 'emergency', 'car'),
	('police4', 'Unmarked Cruiser', 'emergency', 'car'),
	('policeb', 'Police Bike', 'emergency', 'car'),
	('policeold1', 'Police Rancher', 'emergency', 'car'),
	('policeold2', 'Police Roadcruiser', 'emergency', 'car'),
	('policet', 'Police Transporter', 'emergency', 'car'),
	('polmav', 'Police Maverick', 'helicopters', 'air'),
	('pony', 'Pony', 'vans', 'car'),
	('pony2', 'Pony', 'vans', 'car'),
	('postlude', 'Postlude', 'coupes', 'car'),
	('pounder', 'Pounder', 'commercial', 'car'),
	('pounder2', 'Pounder Custom', 'commercial', 'car'),
	('powersurge', 'Powersurge', 'motorcycles', 'car'),
	('prairie', 'Prairie', 'compacts', 'car'),
	('pranger', 'Park Ranger', 'emergency', 'car'),
	('predator', 'Police Predator', 'boats', 'boat'),
	('premier', 'Premier', 'sedans', 'car'),
	('previon', 'Previon', 'coupes', 'car'),
	('primo', 'Primo', 'sedans', 'car'),
	('primo2', 'Primo Custom', 'sedans', 'car'),
	('proptrailer', 'proptrailer', 'utility', 'car'),
	('prototipo', 'X80 Proto', 'super', 'car'),
	('pyro', 'Pyro', 'planes', 'air'),
	('r300', '300R', 'sports', 'car'),
	('radi', 'Radius', 'suvs', 'car'),
	('raiden', 'Raiden', 'sports', 'car'),
	('raketrailer', 'Trailer', 'utility', 'car'),
	('rallytruck', 'Dune', 'service', 'car'),
	('rancherxl', 'Rancher XL', 'off_road', 'car'),
	('rancherxl2', 'Rancher XL', 'off_road', 'car'),
	('rapidgt', 'Rapid GT', 'sports', 'car'),
	('rapidgt2', 'Rapid GT', 'sports', 'car'),
	('rapidgt3', 'Rapid GT Classic', 'sports_classics', 'car'),
	('raptor', 'Raptor', 'sports', 'car'),
	('ratbike', 'Rat Bike', 'motorcycles', 'car'),
	('ratloader', 'Rat-Loader', 'muscle', 'car'),
	('ratloader2', 'Rat-Truck', 'muscle', 'car'),
	('rcbandito', 'RC Bandito', 'off_road', 'car'),
	('reaper', 'Reaper', 'super', 'car'),
	('rebel', 'Rusty Rebel', 'off_road', 'car'),
	('rebel2', 'Rebel', 'off_road', 'car'),
	('rebla', 'Rebla GTS', 'suvs', 'car'),
	('reever', 'Reever', 'motorcycles', 'car'),
	('regina', 'Regina', 'sedans', 'car'),
	('remus', 'Remus', 'sports', 'car'),
	('rentalbus', 'Rental Shuttle Bus', 'service', 'car'),
	('retinue', 'Retinue', 'sports_classics', 'car'),
	('retinue2', 'Retinue Mk II', 'sports_classics', 'car'),
	('revolter', 'Revolter', 'sports', 'car'),
	('rhapsody', 'Rhapsody', 'compacts', 'car'),
	('rhinehart', 'Rhinehart', 'sedans', 'car'),
	('rhino', 'Rhino Tank', 'military', 'car'),
	('riata', 'Riata', 'off_road', 'car'),
	('riot', 'Police Riot', 'emergency', 'car'),
	('riot2', 'RCV', 'emergency', 'car'),
	('ripley', 'Ripley', 'utility', 'car'),
	('rocoto', 'Rocoto', 'suvs', 'car'),
	('rogue', 'Rogue', 'planes', 'air'),
	('romero', 'Romero Hearse', 'sedans', 'car'),
	('rrocket', 'Rampant Rocket', 'motorcycles', 'car'),
	('rt3000', 'RT3000', 'sports', 'car'),
	('rubble', 'Rubble', 'industrial', 'car'),
	('ruffian', 'Ruffian', 'motorcycles', 'car'),
	('ruiner', 'Ruiner', 'muscle', 'car'),
	('ruiner2', 'Ruiner 2000', 'muscle', 'car'),
	('ruiner4', 'Ruiner ZZ-8', 'muscle', 'car'),
	('rumpo', 'Rumpo', 'vans', 'car'),
	('rumpo2', 'Rumpo', 'vans', 'car'),
	('rumpo3', 'Rumpo Custom', 'vans', 'car'),
	('ruston', 'Ruston', 'sports', 'car'),
	('s80', 'S80RR', 'super', 'car'),
	('sabregt', 'Sabre Turbo', 'muscle', 'car'),
	('sabregt2', 'Sabre Turbo Custom', 'muscle', 'car'),
	('sadler', 'Sadler', 'utility', 'car'),
	('sadler2', 'Sadler', 'utility', 'car'),
	('sanchez', 'Sanchez (livery)', 'motorcycles', 'car'),
	('sanchez2', 'Sanchez', 'motorcycles', 'car'),
	('sanctus', 'Sanctus', 'motorcycles', 'car'),
	('sandking', 'Sandking XL', 'off_road', 'car'),
	('sandking2', 'Sandking SWB', 'off_road', 'car'),
	('savage', 'Savage', 'helicopters', 'air'),
	('savestra', 'Savestra', 'sports_classics', 'car'),
	('sc1', 'SC1', 'super', 'car'),
	('scarab', 'Apocalypse Scarab', 'military', 'car'),
	('scarab2', 'Future Shock Scarab', 'military', 'car'),
	('scarab3', 'Nightmare Scarab', 'military', 'car'),
	('schafter2', 'Schafter', 'sedans', 'car'),
	('schafter3', 'Schafter V12', 'sports', 'car'),
	('schafter4', 'Schafter LWB', 'sports', 'car'),
	('schafter5', 'Schafter V12 (Armored)', 'sedans', 'car'),
	('schafter6', 'Schafter LWB (Armored)', 'sedans', 'car'),
	('schlagen', 'Schlagen GT', 'sports', 'car'),
	('schwarzer', 'Schwartzer', 'sports', 'car'),
	('scorcher', 'Scorcher', 'cycles', 'car'),
	('scramjet', 'Scramjet', 'super', 'car'),
	('scrap', 'Scrap Truck', 'utility', 'car'),
	('seabreeze', 'Seabreeze', 'planes', 'air'),
	('seashark', 'Seashark', 'boats', 'boat'),
	('seashark2', 'Seashark', 'boats', 'boat'),
	('seashark3', 'Seashark', 'boats', 'boat'),
	('seasparrow', 'Sea Sparrow', 'helicopters', 'air'),
	('seasparrow2', 'Sparrow', 'helicopters', 'air'),
	('seasparrow3', 'Sparrow', 'helicopters', 'air'),
	('seminole', 'Seminole', 'suvs', 'car'),
	('seminole2', 'Seminole Frontier', 'suvs', 'car'),
	('sentinel', 'Sentinel XS', 'coupes', 'car'),
	('sentinel2', 'Sentinel', 'coupes', 'car'),
	('sentinel3', 'Sentinel Classic', 'sports', 'car'),
	('sentinel4', 'Sentinel Classic Widebody', 'sports', 'car'),
	('serrano', 'Serrano', 'suvs', 'car'),
	('seven70', 'Seven-70', 'sports', 'car'),
	('shamal', 'Shamal', 'planes', 'air'),
	('sheava', 'ETR1', 'super', 'car'),
	('sheriff', 'Sheriff Cruiser', 'emergency', 'car'),
	('sheriff2', 'Sheriff SUV', 'emergency', 'car'),
	('shinobi', 'Shinobi', 'motorcycles', 'car'),
	('shotaro', 'Shotaro', 'motorcycles', 'car'),
	('skylift', 'Skylift', 'helicopters', 'air'),
	('slamtruck', 'Slamtruck', 'utility', 'car'),
	('slamvan', 'Slamvan', 'muscle', 'car'),
	('slamvan2', 'Lost Slamvan', 'muscle', 'car'),
	('slamvan3', 'Slamvan Custom', 'muscle', 'car'),
	('sm722', 'SM722', 'sports', 'car'),
	('sovereign', 'Sovereign', 'motorcycles', 'car'),
	('specter', 'Specter', 'sports', 'car'),
	('specter2', 'Specter Custom', 'sports', 'car'),
	('speeder', 'Speeder', 'boats', 'boat'),
	('speeder2', 'Speeder', 'boats', 'boat'),
	('speedo', 'Speedo', 'vans', 'car'),
	('speedo2', 'Clown Van', 'vans', 'car'),
	('speedo4', 'Speedo Custom', 'vans', 'car'),
	('squaddie', 'Squaddie', 'suvs', 'car'),
	('squalo', 'Squalo', 'boats', 'boat'),
	('stafford', 'Stafford', 'sedans', 'car'),
	('stalion', 'Stallion', 'muscle', 'car'),
	('stalion2', 'Burger Shot Stallion', 'muscle', 'car'),
	('stanier', 'Stanier', 'sedans', 'car'),
	('starling', 'LF-22 Starling', 'planes', 'air'),
	('stinger', 'Stinger', 'sports_classics', 'car'),
	('stingergt', 'Stinger GT', 'sports_classics', 'car'),
	('stockade', 'Stockade', 'commercial', 'car'),
	('stockade3', 'Stockade', 'commercial', 'car'),
	('stratum', 'Stratum', 'sedans', 'car'),
	('streiter', 'Streiter', 'sports', 'car'),
	('stretch', 'Stretch', 'sedans', 'car'),
	('strikeforce', 'B-11 Strikeforce', 'planes', 'air'),
	('stromberg', 'Stromberg', 'sports_classics', 'car'),
	('stryder', 'Stryder', 'motorcycles', 'car'),
	('stunt', 'Mallard', 'planes', 'air'),
	('submersible', 'Submersible', 'boats', 'boat'),
	('submersible2', 'Kraken', 'boats', 'boat'),
	('sugoi', 'Sugoi', 'sports', 'car'),
	('sultan', 'Sultan', 'sports', 'car'),
	('sultan2', 'Sultan Classic', 'sports', 'car'),
	('sultan3', 'Sultan RS Classic', 'sports', 'car'),
	('sultanrs', 'Sultan RS', 'super', 'car'),
	('suntrap', 'Suntrap', 'boats', 'boat'),
	('superd', 'Super Diamond', 'sedans', 'car'),
	('supervolito', 'SuperVolito', 'helicopters', 'air'),
	('supervolito2', 'SuperVolito Carbon', 'helicopters', 'air'),
	('surano', 'Surano', 'sports', 'car'),
	('surfer', 'Surfer', 'vans', 'car'),
	('surfer2', 'Surfer', 'vans', 'car'),
	('surfer3', 'Surfer Custom', 'vans', 'car'),
	('surge', 'Surge', 'sedans', 'car'),
	('swift', 'Swift', 'helicopters', 'air'),
	('swift2', 'Swift Deluxe', 'helicopters', 'air'),
	('swinger', 'Swinger', 'sports_classics', 'car'),
	('t20', 'T20', 'super', 'car'),
	('taco', 'Taco Van', 'vans', 'car'),
	('tahoma', 'Tahoma Coupe', 'muscle', 'car'),
	('tailgater', 'Tailgater', 'sedans', 'car'),
	('tailgater2', 'Tailgater S', 'sedans', 'car'),
	('taipan', 'Taipan', 'super', 'car'),
	('tampa', 'Tampa', 'muscle', 'car'),
	('tampa2', 'Drift Tampa', 'sports', 'car'),
	('tampa3', 'Weaponized Tampa', 'muscle', 'car'),
	('tanker', 'Trailer', 'utility', 'car'),
	('tanker2', 'TANKER', 'utility', 'car'),
	('taxi', 'Taxi', 'service', 'car'),
	('technical', 'Technical', 'off_road', 'car'),
	('technical2', 'Technical Aqua', 'off_road', 'car'),
	('technical3', 'Technical Custom', 'off_road', 'car'),
	('tempesta', 'Tempesta', 'super', 'car'),
	('tenf', '10F', 'sports', 'car'),
	('tenf2', '10F Widebody', 'sports', 'car'),
	('terbyte', 'Terrorbyte', 'commercial', 'car'),
	('tezeract', 'Tezeract', 'super', 'car'),
	('thrax', 'Thrax', 'super', 'car'),
	('thrust', 'Thrust', 'motorcycles', 'car'),
	('thruster', 'Thruster', 'military', 'car'),
	('tigon', 'Tigon', 'super', 'car'),
	('tiptruck', 'Tipper', 'industrial', 'car'),
	('tiptruck2', 'Tipper', 'industrial', 'car'),
	('titan', 'Titan', 'planes', 'air'),
	('toreador', 'Toreador', 'sports_classics', 'car'),
	('torero', 'Torero', 'sports_classics', 'car'),
	('torero2', 'Torero XO', 'super', 'car'),
	('tornado', 'Tornado', 'sports_classics', 'car'),
	('tornado2', 'Tornado', 'sports_classics', 'car'),
	('tornado3', 'Tornado', 'sports_classics', 'car'),
	('tornado4', 'Tornado', 'sports_classics', 'car'),
	('tornado5', 'Tornado Custom', 'sports_classics', 'car'),
	('tornado6', 'Tornado Rat Rod', 'sports_classics', 'car'),
	('toro', 'Toro', 'boats', 'boat'),
	('toro2', 'Toro', 'boats', 'boat'),
	('toros', 'Toros', 'suvs', 'car'),
	('tourbus', 'Tourbus', 'service', 'car'),
	('towtruck', 'Towtruck', 'utility', 'car'),
	('towtruck2', 'Towtruck', 'utility', 'car'),
	('tr2', 'Trailer', 'utility', 'car'),
	('tr3', 'Trailer', 'utility', 'car'),
	('tr4', 'Trailer', 'utility', 'car'),
	('tractor', 'Tractor', 'utility', 'car'),
	('tractor2', 'Fieldmaster', 'utility', 'car'),
	('tractor3', 'Fieldmaster', 'utility', 'car'),
	('trailerlarge', 'Mobile Operations Center', 'utility', 'car'),
	('trailerlogs', 'Trailer', 'utility', 'car'),
	('trailers', 'Trailer', 'utility', 'car'),
	('trailers2', 'Trailer', 'utility', 'car'),
	('trailers3', 'Trailer', 'utility', 'car'),
	('trailers4', 'Trailer', 'utility', 'car'),
	('trailersmall', 'Trailer', 'utility', 'car'),
	('trailersmall2', 'Anti-Aircraft Trailer', 'military', 'car'),
	('trash', 'Trashmaster', 'service', 'car'),
	('trash2', 'Trashmaster', 'service', 'car'),
	('trflat', 'Trailer', 'utility', 'car'),
	('tribike', 'Whippet Race Bike', 'cycles', 'car'),
	('tribike2', 'Endurex Race Bike', 'cycles', 'car'),
	('tribike3', 'Tri-Cycles Race Bike', 'cycles', 'car'),
	('trophytruck', 'Trophy Truck', 'off_road', 'car'),
	('trophytruck2', 'Desert Raid', 'off_road', 'car'),
	('tropic', 'Tropic', 'boats', 'boat'),
	('tropic2', 'Tropic', 'boats', 'boat'),
	('tropos', 'Tropos Rallye', 'sports', 'car'),
	('tug', 'Tug', 'boats', 'boat'),
	('tula', 'Tula', 'planes', 'air'),
	('tulip', 'Tulip', 'muscle', 'car'),
	('tulip2', 'Tulip M-100', 'muscle', 'car'),
	('turismo2', 'Turismo Classic', 'sports_classics', 'car'),
	('turismor', 'Turismo R', 'super', 'car'),
	('tvtrailer', 'Trailer', 'utility', 'car'),
	('tyrant', 'Tyrant', 'super', 'car'),
	('tyrus', 'Tyrus', 'super', 'car'),
	('utillitruck', 'Utility Truck', 'utility', 'car'),
	('utillitruck2', 'Utility Truck', 'utility', 'car'),
	('utillitruck3', 'Utility Truck', 'utility', 'car'),
	('vacca', 'Vacca', 'super', 'car'),
	('vader', 'Vader', 'motorcycles', 'car'),
	('vagner', 'Vagner', 'super', 'car'),
	('vagrant', 'Vagrant', 'off_road', 'car'),
	('valkyrie', 'Valkyrie', 'helicopters', 'air'),
	('valkyrie2', 'Valkyrie MOD.0', 'helicopters', 'air'),
	('vamos', 'Vamos', 'muscle', 'car'),
	('vectre', 'Vectre', 'sports', 'car'),
	('velum', 'Velum', 'planes', 'air'),
	('velum2', 'Velum 5-Seater', 'planes', 'air'),
	('verlierer2', 'Verlierer', 'sports', 'car'),
	('verus', 'Verus', 'off_road', 'car'),
	('vestra', 'Vestra', 'planes', 'air'),
	('vetir', 'Vetir', 'military', 'car'),
	('veto', 'Veto Classic', 'sports', 'car'),
	('veto2', 'Veto Modern', 'sports', 'car'),
	('vigero', 'Vigero', 'muscle', 'car'),
	('vigero2', 'Vigero ZX', 'muscle', 'car'),
	('vigilante', 'Vigilante', 'super', 'car'),
	('vindicator', 'Vindicator', 'motorcycles', 'car'),
	('virgo', 'Virgo', 'muscle', 'car'),
	('virgo2', 'Virgo Classic Custom', 'muscle', 'car'),
	('virgo3', 'Virgo Classic', 'muscle', 'car'),
	('virtue', 'Virtue', 'super', 'car'),
	('viseris', 'Viseris', 'sports_classics', 'car'),
	('visione', 'Visione', 'super', 'car'),
	('volatol', 'Volatol', 'planes', 'air'),
	('volatus', 'Volatus', 'helicopters', 'air'),
	('voltic', 'Voltic', 'super', 'car'),
	('voltic2', 'Rocket Voltic', 'super', 'car'),
	('voodoo', 'Voodoo Custom', 'muscle', 'car'),
	('voodoo2', 'Voodoo', 'muscle', 'car'),
	('vortex', 'Vortex', 'motorcycles', 'car'),
	('vstr', 'V-STR', 'sports', 'car'),
	('warrener', 'Warrener', 'sedans', 'car'),
	('washington', 'Washington', 'sedans', 'car'),
	('wastelander', 'Wastelander', 'service', 'car'),
	('weevil', 'Weevil', 'compacts', 'car'),
	('weevil2', 'Weevil Custom', 'muscle', 'car'),
	('windsor', 'Windsor', 'coupes', 'car'),
	('windsor2', 'Windsor Drop', 'coupes', 'car'),
	('winky', 'Winky', 'off_road', 'car'),
	('wolfsbane', 'Wolfsbane', 'motorcycles', 'car'),
	('xa21', 'XA-21', 'super', 'car'),
	('xls', 'XLS', 'suvs', 'car'),
	('xls2', 'XLS (Armored)', 'suvs', 'car'),
	('yosemite', 'Yosemite', 'muscle', 'car'),
	('yosemite2', 'Drift Yosemite', 'muscle', 'car'),
	('yosemite3', 'Yosemite Rancher', 'off_road', 'car'),
	('youga', 'Youga', 'vans', 'car'),
	('youga2', 'Youga Classic', 'vans', 'car'),
	('youga3', 'Youga Classic 4x4', 'vans', 'car'),
	('youga4', 'Youga Custom', 'vans', 'car'),
	('z190', '190z', 'sports_classics', 'car'),
	('zeno', 'Zeno', 'super', 'car'),
	('zentorno', 'Zentorno', 'super', 'car'),
	('zhaba', 'Zhaba', 'off_road', 'car'),
	('zion', 'Zion', 'coupes', 'car'),
	('zion2', 'Zion Cabrio', 'coupes', 'car'),
	('zion3', 'Zion Classic', 'sports_classics', 'car'),
	('zombiea', 'Zombie Bobber', 'motorcycles', 'car'),
	('zombieb', 'Zombie Chopper', 'motorcycles', 'car'),
	('zorrusso', 'Zorrusso', 'super', 'car'),
	('zr350', 'ZR350', 'sports', 'car'),
	('zr380', 'Apocalypse ZR380', 'sports', 'car'),
	('zr3802', 'Future Shock ZR380', 'sports', 'car'),
	('zr3803', 'Nightmare ZR380', 'sports', 'car'),
	('ztype', 'Z-Type', 'sports_classics', 'car');