----------------------------------
--<!>-- BOII | DEVELOPMENT --<!>--
----------------------------------

-- Language
Language = {
    Targeting = {
        ['animalsicon'] = 'fas fa-utensils',
        ['animalslabel'] = 'Dépecer l\'animal',
    },
    Shared = {
        ['cancel'] = 'Action annulée..',
        ['returnmenu'] = 'Retour',
        ['returnmenuicon'] = 'fa-solid fa-backward',
        ['exitmenu'] = 'Quitter',
        ['exitmenuicon'] = 'fa-solid fa-circle-xmark'
    },
    Skinning = {
        ['noinvent'] = 'On dirait que vos poches sont pleines..',
        ['norange'] = 'Vous êtes trop loin.. rapprochez-vous..',
        ['skinning'] = 'Dépeçage de l\'animal..',
        ['noknife'] = 'Vous avez besoin d\'un couteau pour dépecer cet animal..',
        ['skinned'] = 'Vous avez réussi à dépecer l\'animal !',
        ['notdead'] = 'Vous ne pouvez pas dépecer des animaux qui ne sont pas morts..'
    },
    Stores = {
        Hunting = {
            ['huntingstorelabel'] = 'Chasse SA',
            ['huntingstoreheader'] = 'Chasse SA',
            ['huntingstoreheadertext'] = 'Votre magasin de chasse tout-en-un !',
            ['huntingstoreheadericon'] = 'fa-solid fa-campground',
            ['sellhidesheader'] = 'Vendre Peaux/Fourrures',
            ['sellhidesheadertext'] = 'Consultez les prix actuels des peaux/fourrures !',
            ['sellhidesheadericon'] = 'fa-solid fa-dollar-sign',
            ['openstoreheader'] = 'Ouvrir le Magasin',
            ['openstoreheadertext'] = 'Acheter de l\'équipement de chasse.',
            ['openstoreheadericon'] = 'fa-solid fa-basket-shopping',
            ['nolicense'] = 'Je ne peux pas vous vendre d\'armes si vous n\'avez pas de permis de chasse..',
            ['haslicense'] = 'Permis de chasse validé !',
            ['timer'] = 'Mon service n\'a pas encore commencé. Revenez plus tard, entre '..Config.Stores.Hunting.StartTime..' et '..Config.Stores.Hunting.EndTime..'..'
        },
        Meat = {
            ['meatstoreheader'] = 'Nouilles Sho',
            ['meatstoreheadertext'] = 'Nous achetons de la viande ! N\'importe quelle viande..',
            ['meatstoreheadericon'] = 'fa-solid fa-campground',
            ['sellmeatsheader'] = 'Vendre Viandes',
            ['sellmeatsheadertext'] = 'Consultez les prix actuels de la viande !',
            ['sellmeatsheadericon'] = 'fa-solid fa-dollar-sign',
            ['timer'] = 'Nous n\'avons besoin de rien pour le moment. Revenez plus tard, entre '..Config.Stores.Meat.StartTime..' et '..Config.Stores.Meat.EndTime..'..'
        },
        Exotic = {
            ['eadheader'] = 'Négociant en Animaux Exotiques',
            ['eadheadertext'] = 'Vous cherchez à écouler des marchandises braconnées ?',
            ['eadheadericon'] = 'fab fa-drupal',
            ['sellmeatsheader'] = 'Vendre Viandes',
            ['sellmeatsheadertext'] = 'Consultez les prix actuels de la viande !',
            ['sellmeatsheadericon'] = 'fa-solid fa-dollar-sign',
            ['sellhidesheader'] = 'Vendre Peaux/Fourrures',
            ['sellhidesheadertext'] = 'Consultez les prix actuels des peaux/fourrures !',
            ['sellhidesheadericon'] = 'fa-solid fa-dollar-sign',
            ['timer'] = 'Mon acheteur n\'a besoin de rien pour le moment. Revenez plus tard, entre '..Config.Stores.Exotic.StartTime..' et '..Config.Stores.Exotic.EndTime..'..'
        },
        Selling = {
            ['skinheadericon'] = 'fa-solid fa-paw',
            ['ratskinheader'] = 'Peau de Rat',
            ['ratskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_rat']..'',
            ['rabbitskinheader'] = 'Peau de Lapin',
            ['rabbitskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_rabbit']..'',
            ['pigskinheader'] = 'Peau de Cochon',
            ['pigskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_pig']..'',
            ['cowskinheader'] = 'Peau de Vache',
            ['cowskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_cow']..'',
            ['deerskinheader'] = 'Peau de Cerf',
            ['deerskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_deer']..'',
            ['boarskinheader'] = 'Peau de Sanglier',
            ['boarskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_boar']..'',
            ['coyoteskinheader'] = 'Peau de Coyote',
            ['coyoteskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_coyote']..'',
            ['mtlionskinheader'] = 'Peau de Lion des Montagnes',
            ['mtlionskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_mtlion']..'',
            ['stingrayskinheader'] = 'Peau de Raie',
            ['stingrayskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_stingray']..'',
            ['dolphinskinheader'] = 'Peau de Dauphin',
            ['dolphinskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_dolphin']..'',
            ['sharkskinheader'] = 'Peau de Requin',
            ['sharkskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_shark']..'',
            ['whaleskinheader'] = 'Peau de Baleine',
            ['whaleskinheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['skin_whale']..'',
            ['meatheadericon'] = 'fa-solid fa-bacon',
            ['ratmeatheader'] = 'Viande de Rat',
            ['ratmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_rat']..'',
            ['rabbitmeatheader'] = 'Viande de Lapin',
            ['rabbitmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_rabbit']..'',
            ['chickenhawkmeatheader'] = 'Viande de Buse',
            ['chickenhawkmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_chickenhawk']..'',
            ['cormorantmeatheader'] = 'Viande de Cormoran',
            ['cormorantmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_cormorant']..'',
            ['chickenmeatheader'] = 'Viande de Poulet',
            ['chickenmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_chicken']..'',
            ['pigmeatheader'] = 'Viande de Cochon',
            ['pigmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_pig']..'',
            ['cowmeatheader'] = 'Viande de Vache',
            ['cowmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_cow']..'',
            ['deermeatheader'] = 'Viande de Cerf',
            ['deermeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_deer']..'',
            ['boarmeatheader'] = 'Viande de Sanglier',
            ['boarmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_boar']..'',
            ['coyotemeatheader'] = 'Viande de Coyote',
            ['coyotemeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_coyote']..'',
            ['mtlionmeatheader'] = 'Viande de Lion des Montagnes',
            ['mtlionmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_mtlion']..'',
            ['stingraymeatheader'] = 'Viande de Raie',
            ['stingraymeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_stingray']..'',
            ['dolphinmeatheader'] = 'Viande de Dauphin',
            ['dolphinmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_dolphin']..'',
            ['sharkmeatheader'] = 'Viande de Requin',
            ['sharkmeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_shark']..'',
            ['whalemeatheader'] = 'Viande de Baleine',
            ['whalemeatheadertext'] = 'Prix: $'..Config.Stores.Selling.Prices['meat_whale']..'',
            ['noitems'] = 'On dirait que vous n\'avez rien à vendre..'
        }
    }
}